// Generated by cbindgen. DO NOT EDIT.

#ifndef BLACKBIRD_CORE_H
#define BLACKBIRD_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

#define BOLD (1 << 0)

#define ITALIC (1 << 1)

#define UNDERLINE (1 << 2)

#define REVERSE (1 << 3)

#define DIM (1 << 4)

#define STRIKE (1 << 5)

#define ALT_SCREEN (1 << 0)

#define APP_CURSOR (1 << 1)

#define APP_KEYPAD (1 << 2)

#define BRACKETED_PASTE (1 << 3)

#define MOUSE_REPORT_CLICK (1 << 4)

#define MOUSE_MOTION (1 << 5)

#define MOUSE_DRAG (1 << 6)

#define SGR_MOUSE (1 << 7)

#define FOCUS_IN_OUT (1 << 8)

#define SHOW_CURSOR (1 << 9)

#define LINE_WRAP (1 << 10)

/**
 * Kind of terminal event forwarded to the C caller.
 */
enum BBEventKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  BB_EVENT_KIND_TITLE = 1,
  BB_EVENT_KIND_BELL = 2,
  /**
   * Reserved for future use. Not currently emitted by RoutingListener —
   * alacritty 0.26 doesn't surface cursor-shape changes as events. Swift
   * readers should consume cursor state from snapshots.
   */
  BB_EVENT_KIND_CURSOR_SHAPE = 3,
  BB_EVENT_KIND_OSC52_CLIPBOARD = 4,
  /**
   * Bytes that should be written BACK to the PTY (terminal → shell).
   * alacritty_terminal generates these in response to DSR queries (ESC[6n),
   * DA1/DA2, DECRPM, and similar terminal-identification sequences. If the
   * host ignores these, apps like nvim that probe terminal capabilities
   * will time out waiting for a response.
   */
  BB_EVENT_KIND_PTY_WRITE = 5,
  BB_EVENT_KIND_FATAL = 99,
};
#ifndef __cplusplus
typedef uint32_t BBEventKind;
#endif // __cplusplus

/**
 * Opaque handle exposed to Swift.
 *
 * SAFETY: Rust drops struct fields in declaration order. `term` owns a
 * RoutingListener whose raw pointer targets `callback`, so `term` must be
 * declared BEFORE `callback` — this makes `term` drop first, leaving the
 * pointer valid during Term's destruction. The Fatal event delivery path
 * (in `guard_with_term`) fires during teardown, making this ordering
 * load-bearing.
 */
struct BBTerm;

/**
 * Event forwarded to the C callback.
 *
 * `payload` is valid **only for the duration of the callback**; callers must
 * copy the bytes if they need them after the callback returns.
 */
struct BBEvent {
  BBEventKind kind;
  /**
   * Borrowed pointer into Rust-owned memory; null when `len == 0`.
   */
  const uint8_t *payload;
  uintptr_t len;
  /**
   * Cursor-shape variant: 0 = block, 1 = bar, 2 = underline; 0 otherwise.
   */
  int32_t i32_arg;
};

/**
 * Flat cell layout for cross-language consumption. Swift reads these directly.
 */
struct BBCell {
  uint32_t ch;
  uint32_t fg;
  uint32_t bg;
  uint16_t flags;
  uint16_t _reserved;
};

/**
 * Immutable snapshot of terminal grid state. Ref-counted via `bb_snap_retain` /
 * `bb_snap_release`. The `cells` pointer is stable for the lifetime of the snapshot.
 *
 * `cells` is non-null and points to exactly `cells_len` consecutive `BBCell` elements for the
 * lifetime of this snapshot. It is never null for any snapshot returned by
 * `bb_term_take_snapshot`, because `bb_term_new` rejects zero dimensions and `display_iter()`
 * always yields `cols * rows` cells.
 *
 * The actual heap allocation is `BBSnapOwned`; the raw pointer exposed to C points to the
 * `snap` field at offset 0 of that struct. Do not construct or free `BBSnap` directly.
 */
struct BBSnap {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  uint16_t cursor_row;
  uint8_t cursor_visible;
  uint8_t _pad[3];
  uint32_t mode;
  uintptr_t cells_len;
  const struct BBCell *cells;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new terminal. Returns null on invalid input or internal error.
 *
 * # Safety
 * The returned pointer must be freed exactly once via `bb_term_free`.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available yet to deliver a Fatal event).
 * The function returns null as the fallback value.
 */
struct BBTerm *bb_term_new(uint16_t cols, uint16_t rows, uint32_t scrollback);

/**
 * Free a terminal handle created by `bb_term_new`.
 *
 * # Safety
 * `term` must have been returned by `bb_term_new` and not previously freed.
 * Passing null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no safe `BBTerm` context is available during teardown to deliver
 * a Fatal event). The function returns unit as the fallback value.
 */
void bb_term_free(struct BBTerm *term);

/**
 * Feed `len` bytes from `bytes` into the terminal's VT parser.
 *
 * # Safety
 * - `term` must be non-null, properly aligned (obtained from `bb_term_new`),
 *   and not freed for the duration of this call.
 * - `bytes` must be non-null when `len > 0` and point to a readable region of
 *   at least `len` bytes. Passing `bytes = null, len = 0` is safe (no-op).
 * - No two threads may call any `bb_term_*` function concurrently on the same
 *   `term`; interior state is mutated and `Term`/`Processor` are not `Sync`.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_input(struct BBTerm *term, const uint8_t *bytes, uintptr_t len);

/**
 * Resize the terminal grid. Out-of-range (zero) dimensions are ignored.
 *
 * # Safety
 * `term` must be a valid non-null pointer from `bb_term_new`, properly
 * aligned, not freed for the duration of the call. No concurrent calls on
 * the same term.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_resize(struct BBTerm *term, uint16_t cols, uint16_t rows);

/**
 * Register (or clear) the event callback for a terminal.
 *
 * Pass `cb = None` to disable event delivery.  `ctx` is an opaque pointer
 * forwarded verbatim to every callback invocation; pass `null` if unused.
 *
 * # Safety
 * - `term` must be non-null, valid, and not freed while the callback is
 *   registered.
 * - `ctx` must remain valid for all subsequent `bb_term_input` calls until
 *   the callback is cleared or the terminal is freed.
 * - The callback may be invoked synchronously from within `bb_term_input`;
 *   it must not call any `bb_term_*` function on the same `term` handle
 *   (no re-entrant use).
 * - All access must occur on the same thread (no concurrent calls on the
 *   same term).
 * - Passing `term = null` is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_set_event_cb(struct BBTerm *term, void (*cb)(struct BBEvent, void*), void *ctx);

/**
 * Take an immutable snapshot of the current grid state.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Returns null on null input.
 * The returned pointer must be released by exactly one `bb_snap_release` per
 * successful call (plus one per `bb_snap_retain`).
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * null as the fallback value.
 */
const struct BBSnap *bb_term_take_snapshot(struct BBTerm *term);

/**
 * Increment refcount. Returns the input pointer for fluent usage.
 *
 * # Safety
 * `snap` must be a pointer returned by `bb_term_take_snapshot` or previously
 * retained, and not yet released to zero. Null is a no-op (returns null).
 * Safe to call from any thread.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns the input
 * `snap` pointer as the fallback value.
 */
const struct BBSnap *bb_snap_retain(const struct BBSnap *snap);

/**
 * Decrement refcount; free when it reaches zero.
 *
 * # Safety
 * Each `snap` must be released exactly once per acquire (new or retain).
 * Null is a no-op. Safe to call from any thread, but each concrete handle
 * follows the acquire/release discipline documented above.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns unit as
 * the fallback value.
 */
void bb_snap_release(const struct BBSnap *snap);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLACKBIRD_CORE_H */
