// Generated by cbindgen. DO NOT EDIT.

#ifndef BLACKBIRD_CORE_H
#define BLACKBIRD_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

#define BOLD (1 << 0)

#define ITALIC (1 << 1)

#define UNDERLINE (1 << 2)

#define REVERSE (1 << 3)

#define DIM (1 << 4)

#define STRIKE (1 << 5)

/**
 * Cell holds the left half of a wide (double-width) glyph — CJK, some
 * emoji, and private-use ranges like Nerd Font glyphs tagged wide. The
 * renderer draws the glyph from this cell occupying two cell widths.
 */
#define WIDE_CHAR (1 << 6)

/**
 * Cell is the right half of a wide glyph — the renderer must not draw
 * a glyph here (the wide one in the preceding cell already covers it).
 * Filling this cell with a space overpaints the CJK/emoji character.
 */
#define WIDE_CHAR_SPACER (1 << 7)

/**
 * Cell is the unused column to the LEFT of a wide glyph that wrapped
 * because only one column remained on the prior row. Same rule as
 * WIDE_CHAR_SPACER — don't draw.
 */
#define LEADING_WIDE_CHAR_SPACER (1 << 8)

/**
 * CSI 21 m — double underline. Mutually exclusive with the other four
 * underline style bits at the alacritty level (`ALL_UNDERLINES` mask).
 */
#define UNDERLINE_DOUBLE (1 << 9)

/**
 * CSI 4:3 m — wavy / undercurl. Neovim/Helix LSP diagnostics emit this
 * for warnings/errors; having it rendered correctly matters for the
 * agentic-CLI correctness wedge.
 */
#define UNDERCURL (1 << 10)

/**
 * CSI 4:4 m — dotted underline.
 */
#define UNDERLINE_DOTTED (1 << 11)

/**
 * CSI 4:5 m — dashed underline.
 */
#define UNDERLINE_DASHED (1 << 12)

#define ALT_SCREEN (1 << 0)

#define APP_CURSOR (1 << 1)

#define APP_KEYPAD (1 << 2)

#define BRACKETED_PASTE (1 << 3)

#define MOUSE_REPORT_CLICK (1 << 4)

#define MOUSE_MOTION (1 << 5)

#define MOUSE_DRAG (1 << 6)

#define SGR_MOUSE (1 << 7)

#define FOCUS_IN_OUT (1 << 8)

#define SHOW_CURSOR (1 << 9)

#define LINE_WRAP (1 << 10)

#define DISAMBIGUATE_ESC_CODES (1 << 11)

#define REPORT_EVENT_TYPES (1 << 12)

#define REPORT_ALTERNATE_KEYS (1 << 13)

#define REPORT_ALL_KEYS_AS_ESC (1 << 14)

#define REPORT_ASSOCIATED_TEXT (1 << 15)

/**
 * Kind of terminal event forwarded to the C caller.
 */
enum BBEventKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  BB_EVENT_KIND_TITLE = 1,
  BB_EVENT_KIND_BELL = 2,
  /**
   * Reserved for future use. Not currently emitted by RoutingListener —
   * alacritty 0.26 doesn't surface cursor-shape changes as events. Swift
   * readers should consume cursor state from snapshots.
   */
  BB_EVENT_KIND_CURSOR_SHAPE = 3,
  BB_EVENT_KIND_OSC52_CLIPBOARD = 4,
  /**
   * Bytes that should be written BACK to the PTY (terminal → shell).
   * alacritty_terminal generates these in response to DSR queries (ESC[6n),
   * DA1/DA2, DECRPM, and similar terminal-identification sequences. If the
   * host ignores these, apps like nvim that probe terminal capabilities
   * will time out waiting for a response.
   */
  BB_EVENT_KIND_PTY_WRITE = 5,
  /**
   * New in 2026-04-17 gaps plan. Payload: UTF-8 bytes of the local
   * filesystem path decoded from an OSC 7 `file://` URL. Only emitted
   * when scheme is `file` and authority is empty or `localhost`.
   *
   * OSC 7 is not parsed by `alacritty_terminal` 0.26 / `vte` 0.15 —
   * the sequence falls through vte's `osc_dispatch` unhandled branch.
   * We run a parallel `vte::Parser` in `bb_term_input` against an
   * `Osc7Scanner` that fires only on this one sequence. See the
   * scanner impl and the fragmentation test for details.
   */
  BB_EVENT_KIND_CWD_CHANGED = 6,
  BB_EVENT_KIND_FATAL = 99,
};
#ifndef __cplusplus
typedef uint32_t BBEventKind;
#endif // __cplusplus

/**
 * Opaque handle exposed to Swift.
 *
 * SAFETY: Rust drops struct fields in declaration order. `term` owns a
 * RoutingListener whose raw pointer targets `callback`, so `term` must be
 * declared BEFORE `callback` — this makes `term` drop first, leaving the
 * pointer valid during Term's destruction. The Fatal event delivery path
 * (in `guard_with_term`) fires during teardown, making this ordering
 * load-bearing.
 */
struct BBTerm;

/**
 * Event forwarded to the C callback.
 *
 * `payload` is valid **only for the duration of the callback**; callers must
 * copy the bytes if they need them after the callback returns.
 */
struct BBEvent {
  BBEventKind kind;
  /**
   * Borrowed pointer into Rust-owned memory; null when `len == 0`.
   */
  const uint8_t *payload;
  uintptr_t len;
  /**
   * Cursor-shape variant: 0 = block, 1 = bar, 2 = underline; 0 otherwise.
   */
  int32_t i32_arg;
};

/**
 * Flat cell layout for cross-language consumption. Swift reads these directly.
 */
struct BBCell {
  uint32_t ch;
  uint32_t fg;
  uint32_t bg;
  uint16_t flags;
  /**
   * Index into `BBSnap::links` (0 means no OSC 8 attribution on this cell).
   * Resolve via `bb_snap_link_url(snap, link_id)`.
   */
  uint16_t link_id;
};

/**
 * Immutable snapshot of terminal grid state. Ref-counted via `bb_snap_retain` /
 * `bb_snap_release`. The `cells` pointer is stable for the lifetime of the snapshot.
 *
 * `cells` is non-null and points to exactly `cells_len` consecutive `BBCell` elements for the
 * lifetime of this snapshot. It is never null for any snapshot returned by
 * `bb_term_take_snapshot`, because `bb_term_new` rejects zero dimensions and `display_iter()`
 * always yields `cols * rows` cells.
 *
 * The actual heap allocation is `BBSnapOwned`; the raw pointer exposed to C points to the
 * `snap` field at offset 0 of that struct. Do not construct or free `BBSnap` directly.
 */
struct BBSnap {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  uint16_t cursor_row;
  uint8_t cursor_visible;
  uint8_t _pad;
  /**
   * Number of lines the viewport is scrolled above the live grid. 0 means
   * we're pinned to the bottom (live content). When > 0 the renderer must
   * offset the cursor by this amount or hide it if the live cursor row is
   * no longer visible.
   */
  uint16_t display_offset;
  uint32_t mode;
  uintptr_t cells_len;
  const struct BBCell *cells;
  /**
   * Total lines currently retained in scrollback (grows as output flows
   * off-screen, capped at the scrollback limit). Used by the scroll
   * indicator to size its thumb proportional to total-buffer vs viewport.
   * Appended here to preserve the existing offsets of cells_len/cells.
   */
  uint32_t history_size;
  /**
   * DECSCUSR cursor shape: 0 = block, 1 = bar/beam, 2 = underline, 3 = hidden.
   * Sourced from `Term::cursor_style().shape` at snapshot time. Callers
   * render according to this; a value of 3 means the renderer should skip
   * drawing the cursor entirely.
   */
  uint8_t cursor_shape;
  uint8_t _pad2b[3];
};

/**
 * Owned UTF-8 byte buffer returned from text-extraction FFIs.
 *
 * `bytes`/`len` describe a read-only view into the heap buffer whose raw
 * parts are stored in `_owned_ptr` / `_owned_cap`. The Rust side
 * heap-allocates a `Box<BBString>`, builds the payload as a `Vec<u8>`, then
 * decomposes the vec (ptr + capacity) and installs the pointer into
 * `bytes`. Callers must free via `bb_string_release` exactly once; nothing
 * else keeps the backing allocation alive.
 *
 * The `_owned_*` fields are intentionally present in the C-visible layout
 * to keep the struct self-contained (one `Box<BBString>` + one `Vec<u8>`
 * buffer, freed together by `bb_string_release`). Consumers on the C side
 * should read only `bytes` and `len` and otherwise treat the struct as
 * opaque — never poke into the owned fields. Using raw pointer + capacity
 * instead of a literal `Vec<u8>` field lets cbindgen emit a complete,
 * FFI-safe layout that Swift can import: `Vec<u8>` is not `repr(C)`, so a
 * `Vec` field would surface as an incomplete type in the generated header.
 */
struct BBString {
  const uint8_t *bytes;
  uintptr_t len;
  uint8_t *_owned_ptr;
  uintptr_t _owned_cap;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new terminal. Returns null on invalid input or internal error.
 *
 * # Safety
 * The returned pointer must be freed exactly once via `bb_term_free`.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available yet to deliver a Fatal event).
 * The function returns null as the fallback value.
 */
struct BBTerm *bb_term_new(uint16_t cols, uint16_t rows, uint32_t scrollback);

/**
 * Free a terminal handle created by `bb_term_new`.
 *
 * # Safety
 * `term` must have been returned by `bb_term_new` and not previously freed.
 * Passing null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no safe `BBTerm` context is available during teardown to deliver
 * a Fatal event). The function returns unit as the fallback value.
 */
void bb_term_free(struct BBTerm *term);

/**
 * Feed `len` bytes from `bytes` into the terminal's VT parser.
 *
 * # Safety
 * - `term` must be non-null, properly aligned (obtained from `bb_term_new`),
 *   and not freed for the duration of this call.
 * - `bytes` must be non-null when `len > 0` and point to a readable region of
 *   at least `len` bytes. Passing `bytes = null, len = 0` is safe (no-op).
 * - No two threads may call any `bb_term_*` function concurrently on the same
 *   `term`; interior state is mutated and `Term`/`Processor` are not `Sync`.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_input(struct BBTerm *term, const uint8_t *bytes, uintptr_t len);

/**
 * Resize the terminal grid. Out-of-range (zero) dimensions are ignored.
 *
 * # Safety
 * `term` must be a valid non-null pointer from `bb_term_new`, properly
 * aligned, not freed for the duration of the call. No concurrent calls on
 * the same term.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_resize(struct BBTerm *term, uint16_t cols, uint16_t rows);

/**
 * Register (or clear) the event callback for a terminal.
 *
 * Pass `cb = None` to disable event delivery.  `ctx` is an opaque pointer
 * forwarded verbatim to every callback invocation; pass `null` if unused.
 *
 * # Safety
 * - `term` must be non-null, valid, and not freed while the callback is
 *   registered.
 * - `ctx` must remain valid for all subsequent `bb_term_input` calls until
 *   the callback is cleared or the terminal is freed.
 * - The callback may be invoked synchronously from within `bb_term_input`;
 *   it must not call any `bb_term_*` function on the same `term` handle
 *   (no re-entrant use).
 * - All access must occur on the same thread (no concurrent calls on the
 *   same term).
 * - Passing `term = null` is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_set_event_cb(struct BBTerm *term, void (*cb)(struct BBEvent, void*), void *ctx);

/**
 * Take an immutable snapshot of the current grid state.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Returns null on null input.
 * The returned pointer must be released by exactly one `bb_snap_release` per
 * successful call (plus one per `bb_snap_retain`).
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * null as the fallback value.
 */
const struct BBSnap *bb_term_take_snapshot(struct BBTerm *term);

/**
 * Increment refcount. Returns the input pointer for fluent usage.
 *
 * # Safety
 * `snap` must be a pointer returned by `bb_term_take_snapshot` or previously
 * retained, and not yet released to zero. Null is a no-op (returns null).
 * Safe to call from any thread.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns the input
 * `snap` pointer as the fallback value.
 */
const struct BBSnap *bb_snap_retain(const struct BBSnap *snap);

/**
 * Decrement refcount; free when it reaches zero.
 *
 * # Safety
 * Each `snap` must be released exactly once per acquire (new or retain).
 * Null is a no-op. Safe to call from any thread, but each concrete handle
 * follows the acquire/release discipline documented above.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns unit as
 * the fallback value.
 */
void bb_snap_release(const struct BBSnap *snap);

/**
 * Look up the OSC 8 link id at a snapshot cell. Returns 0 when `snap` is
 * null, `(row, col)` is outside the grid, or the cell has no OSC 8
 * attribution.
 *
 * Pass the returned non-zero id to `bb_snap_link_url` to get the URL.
 *
 * # Safety
 * `snap` must be non-null and returned by `bb_term_take_snapshot` /
 * `bb_snap_retain`, not yet released to zero.
 */
uint32_t bb_snap_link_id_at(const struct BBSnap *snap, uint16_t row, uint16_t col);

/**
 * Resolve an OSC 8 link id to its UTF-8 URL. Returns null when `snap` is
 * null, `link_id == 0`, or the id is unknown. The returned pointer is
 * valid for the snapshot's lifetime (until the matching `bb_snap_release`
 * drops the refcount to zero).
 *
 * # Safety
 * `snap` must be non-null and returned by `bb_term_take_snapshot` /
 * `bb_snap_retain`, not yet released to zero.
 */
const char *bb_snap_link_url(const struct BBSnap *snap, uint32_t link_id);

/**
 * Scroll the display by `delta` lines. Positive = scroll up (show older
 * content), negative = scroll down (show newer content, towards bottom).
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Passing null or delta == 0 is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_scroll(struct BBTerm *term, int32_t delta);

/**
 * Snap the viewport back to the live grid (display_offset = 0). Called after
 * any user keystroke so typing/Enter always brings them back from scrollback
 * history. A no-op if already at the bottom.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_scroll_to_bottom(struct BBTerm *term);

/**
 * Clear the visible screen AND the scrollback, moving the cursor to the
 * top-left. Implemented by feeding the VT sequences directly to the
 * parser (same path a shell's `clear` would take), so the rest of the
 * terminal state (palette, cursor color, etc.) is untouched.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null is a no-op.
 */
void bb_term_clear_all(struct BBTerm *term);

/**
 * Update one slot of the terminal's color palette. Slot indices match
 * alacritty's `NamedColor` ordering: 0..=15 = 16 ANSI colors, 16..=255 =
 * extended 256-palette, 256 = Foreground, 257 = Background, 258 = Cursor,
 * 259 = BrightForeground, plus a few more (see alacritty's NamedColor enum).
 * `rgb` is packed 0xRRGGBB.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null `term` is a no-op. Slots
 * beyond alacritty's palette length are silently ignored.
 */
void bb_term_set_named_color(struct BBTerm *term, uint16_t slot, uint32_t rgb);

/**
 * Extract UTF-8 text from the terminal buffer between two buffer-relative
 * points. `start_line`/`end_line` are grid lines where 0 is the top of the
 * visible viewport and negative values reach into scrollback (buffer-relative,
 * matching alacritty's `Line(i32)` convention).
 *
 * `rect == 0` selects prose mode: the first line is emitted from `start_col`
 * to the end of the row, the last line from column 0 to `end_col`, and
 * middle lines are taken in full. Trailing spaces are trimmed from every
 * line except the last to avoid pulling the grid's blank fill into copied
 * output.
 *
 * `rect != 0` selects rectangular mode: every line is clipped to
 * `[start_col, end_col]` with no trimming.
 *
 * `\0` cells (alacritty's "unrendered" sentinel) are emitted as spaces. Real
 * spaces come through as-is. Lines outside `[topmost_line, bottommost_line]`
 * are skipped silently. Points are normalized so `(start_line, start_col)
 * <= (end_line, end_col)` before iterating.
 *
 * Returns a heap-allocated `BBString` the caller must free with
 * `bb_string_release`. Returns null when `term` is null.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Caller owns the returned pointer.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * null as the fallback value.
 */
struct BBString *bb_term_text_range(struct BBTerm *term,
                                    int32_t start_line,
                                    uint16_t start_col,
                                    int32_t end_line,
                                    uint16_t end_col,
                                    uint8_t rect);

/**
 * Free a `BBString` returned by `bb_term_text_range`.
 *
 * Rebuilds the owned `Vec<u8>` from `_owned_ptr`/`_owned_cap`/`len` so its
 * heap buffer is deallocated with the matching `Vec` allocator, then drops
 * the `Box<BBString>`.
 *
 * # Safety
 * `s` must have been returned by `bb_term_text_range` and not previously
 * released. Passing null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns unit as
 * the fallback value.
 */
void bb_string_release(struct BBString *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLACKBIRD_CORE_H */
