// Generated by cbindgen. DO NOT EDIT.

#ifndef BLACKBIRD_CORE_H
#define BLACKBIRD_CORE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stddef.h>

/**
 * Sentinel for `BBCell::underline_color` meaning "no explicit underline
 * colour set; use the cell's fg". Chosen as u32::MAX because alacritty's
 * RGB representation tops out at 0x00FF_FFFF and 0xFF000000 bits are
 * otherwise unused — picking a sentinel outside the valid RGB range avoids
 * a flag bit.
 */
#define UNDERLINE_COLOR_UNSET 4294967295

/**
 * Magic sentinel stamped into `BBString::_magic` on construction. Any
 * 64-bit constant unlikely to appear on the heap by accident. Also
 * invariant-encodes the string "BlackbirdStr" via the low byte pattern.
 */
#define BB_STRING_MAGIC 12802708709476227040ull

#define BOLD (1 << 0)

#define ITALIC (1 << 1)

#define UNDERLINE (1 << 2)

#define REVERSE (1 << 3)

#define DIM (1 << 4)

#define STRIKE (1 << 5)

/**
 * Cell holds the left half of a wide (double-width) glyph — CJK, some
 * emoji, and private-use ranges like Nerd Font glyphs tagged wide. The
 * renderer draws the glyph from this cell occupying two cell widths.
 */
#define WIDE_CHAR (1 << 6)

/**
 * Cell is the right half of a wide glyph — the renderer must not draw
 * a glyph here (the wide one in the preceding cell already covers it).
 * Filling this cell with a space overpaints the CJK/emoji character.
 */
#define WIDE_CHAR_SPACER (1 << 7)

/**
 * Cell is the unused column to the LEFT of a wide glyph that wrapped
 * because only one column remained on the prior row. Same rule as
 * WIDE_CHAR_SPACER — don't draw.
 */
#define LEADING_WIDE_CHAR_SPACER (1 << 8)

/**
 * CSI 21 m — double underline. Mutually exclusive with the other four
 * underline style bits at the alacritty level (`ALL_UNDERLINES` mask).
 */
#define UNDERLINE_DOUBLE (1 << 9)

/**
 * CSI 4:3 m — wavy / undercurl. Neovim/Helix LSP diagnostics emit this
 * for warnings/errors; having it rendered correctly matters for the
 * agentic-CLI correctness wedge.
 */
#define UNDERCURL (1 << 10)

/**
 * CSI 4:4 m — dotted underline.
 */
#define UNDERLINE_DOTTED (1 << 11)

/**
 * CSI 4:5 m — dashed underline.
 */
#define UNDERLINE_DASHED (1 << 12)

#define ALT_SCREEN (1 << 0)

#define APP_CURSOR (1 << 1)

#define APP_KEYPAD (1 << 2)

#define BRACKETED_PASTE (1 << 3)

#define MOUSE_REPORT_CLICK (1 << 4)

#define MOUSE_MOTION (1 << 5)

#define MOUSE_DRAG (1 << 6)

#define SGR_MOUSE (1 << 7)

#define FOCUS_IN_OUT (1 << 8)

#define SHOW_CURSOR (1 << 9)

#define LINE_WRAP (1 << 10)

#define DISAMBIGUATE_ESC_CODES (1 << 11)

#define REPORT_EVENT_TYPES (1 << 12)

#define REPORT_ALTERNATE_KEYS (1 << 13)

#define REPORT_ALL_KEYS_AS_ESC (1 << 14)

#define REPORT_ASSOCIATED_TEXT (1 << 15)

/**
 * xterm `modifyOtherKeys` level ≥ 1 is active. Enabled by
 * `CSI > 4 ; 1 m` or `CSI > 4 ; 2 m`; cleared by `CSI > 4 ; 0 m`.
 * Blackbird treats both non-zero levels as "on" — Emacs asks for
 * level 2; level 1's gating table is historical and rarely requested
 * in practice. When on, the KeyEncoder emits
 * `CSI 27 ; <mod> ; <cp> ~` for modified printables + control-code
 * colliders (Tab/Enter/Esc/Backspace) instead of raw bytes. See
 * <https://invisible-island.net/xterm/modified-keys.html>.
 *
 * Precedence: Kitty flags (if any set) take priority over
 * modifyOtherKeys. A TUI that pushes Kitty gets Kitty output;
 * Emacs without Kitty gets modifyOtherKeys output.
 */
#define MODIFY_OTHER_KEYS (1 << 16)

/**
 * Kind of terminal event forwarded to the C caller.
 */
enum BBEventKind
#ifdef __cplusplus
  : uint32_t
#endif // __cplusplus
 {
  BB_EVENT_KIND_TITLE = 1,
  BB_EVENT_KIND_BELL = 2,
  /**
   * Reserved for future use. Not currently emitted by RoutingListener —
   * alacritty 0.26 doesn't surface cursor-shape changes as events. Swift
   * readers should consume cursor state from snapshots.
   */
  BB_EVENT_KIND_CURSOR_SHAPE = 3,
  BB_EVENT_KIND_OSC52_CLIPBOARD = 4,
  /**
   * Bytes that should be written BACK to the PTY (terminal → shell).
   * alacritty_terminal generates these in response to DSR queries (ESC[6n),
   * DA1/DA2, DECRPM, and similar terminal-identification sequences. If the
   * host ignores these, apps like nvim that probe terminal capabilities
   * will time out waiting for a response.
   */
  BB_EVENT_KIND_PTY_WRITE = 5,
  /**
   * New in 2026-04-17 gaps plan. Payload: UTF-8 bytes of the local
   * filesystem path decoded from an OSC 7 `file://` URL. Only emitted
   * when scheme is `file` and authority is empty or `localhost`.
   *
   * OSC 7 is not parsed by `alacritty_terminal` 0.26 / `vte` 0.15 —
   * the sequence falls through vte's `osc_dispatch` unhandled branch.
   * We run a parallel `vte::Parser` in `bb_term_input` against an
   * `Osc7Scanner` that fires only on this one sequence. See the
   * scanner impl and the fragmentation test for details.
   */
  BB_EVENT_KIND_CWD_CHANGED = 6,
  /**
   * OSC 133 prompt/command mark emitted by a shell-integration snippet
   * (bash/zsh/fish). `i32_arg` carries the kind: 1=A (prompt start),
   * 2=B (command start), 3=C (command output start), 4=D (command end).
   * `payload` is the ASCII decimal exit code for kind D, empty otherwise.
   */
  BB_EVENT_KIND_PROMPT_MARK = 7,
  BB_EVENT_KIND_FATAL = 99,
};
#ifndef __cplusplus
typedef uint32_t BBEventKind;
#endif // __cplusplus

/**
 * Opaque handle exposed to Swift.
 *
 * `callback` and `color_queue` are shared with the owned `Term`'s
 * `RoutingListener` via `Arc`. Field drop order between `term` and the
 * cells is no longer load-bearing for memory safety (rust-core-1 F3):
 * each Arc keeps its inner cell alive as long as any clone exists, so an
 * event firing during `Term`'s destruction still lands on live memory.
 */
struct BBTerm;

/**
 * Result of `bb_term_resize2`. `applied_cols` / `applied_rows` report the
 * dimensions the grid was actually resized to after clamping (floor = 2,
 * ceiling = 1000 on each axis); `clamped` is non-zero when either requested
 * dim differed from the applied value. On a no-op call (null term, or zero
 * in either dim) all three fields are `0`.
 */
struct BBResizeResult {
  uint16_t applied_cols;
  uint16_t applied_rows;
  /**
   * Non-zero when the request was rewritten by the clamp; zero when the
   * grid now holds exactly the requested dims (or on no-op).
   */
  uint8_t clamped;
  uint8_t _pad[3];
};

/**
 * Event forwarded to the C callback.
 *
 * `payload` is valid **only for the duration of the callback**; callers must
 * copy the bytes if they need them after the callback returns.
 */
struct BBEvent {
  BBEventKind kind;
  /**
   * Borrowed pointer into Rust-owned memory; null when `len == 0`.
   */
  const uint8_t *payload;
  uintptr_t len;
  /**
   * Cursor-shape variant: 0 = block, 1 = bar, 2 = underline; 0 otherwise.
   */
  int32_t i32_arg;
};

/**
 * Flat cell layout for cross-language consumption. Swift reads these directly.
 */
struct BBCell {
  uint32_t ch;
  uint32_t fg;
  uint32_t bg;
  uint16_t flags;
  /**
   * Index into `BBSnap::links` (0 means no OSC 8 attribution on this cell).
   * Resolve via `bb_snap_link_url(snap, link_id)`.
   */
  uint16_t link_id;
  /**
   * CSI 58 colored-underline — the user may explicitly set the underline's
   * colour independent of the glyph fg. alacritty 0.26 stores this as
   * `Option<Color>` on the cell's extra; we flatten to a u32 with a magic
   * sentinel: `UNDERLINE_COLOR_UNSET` (0xFFFF_FFFF) means "follow fg".
   * Any other value is `0x00RRGGBB`.
   *
   * Ignored unless at least one underline-style bit is set in `flags`.
   * Widens BBCell from 16 to 20 bytes — still 4-aligned, still fast to
   * iterate over 16k cells.
   */
  uint32_t underline_color;
};

/**
 * Immutable snapshot of terminal grid state. Ref-counted via `bb_snap_retain` /
 * `bb_snap_release`. The `cells` pointer is stable for the lifetime of the snapshot.
 *
 * `cells` is non-null and points to exactly `cells_len` consecutive `BBCell` elements for the
 * lifetime of this snapshot. It is never null for any snapshot returned by
 * `bb_term_take_snapshot`, because `bb_term_new` rejects zero dimensions and `display_iter()`
 * always yields `cols * rows` cells.
 *
 * The actual heap allocation is `BBSnapOwned`; the raw pointer exposed to C points to the
 * `snap` field at offset 0 of that struct. Do not construct or free `BBSnap` directly.
 */
struct BBSnap {
  uint16_t cols;
  uint16_t rows;
  uint16_t cursor_col;
  uint16_t cursor_row;
  uint8_t cursor_visible;
  /**
   * Pads `display_offset` (u32) to a 4-byte boundary. Without this
   * the field would land at offset 9 and Rust's repr(C) would
   * inject 3 bytes of implicit padding that cbindgen wouldn't
   * reflect in the header — Swift would then read a mis-offset
   * field. Explicit padding keeps the C and Rust layouts in lock-
   * step. (Pre-M5 this was 1 byte aligning the previous u16.)
   */
  uint8_t _pad[3];
  /**
   * Number of lines the viewport is scrolled above the live grid. 0 means
   * we're pinned to the bottom (live content). When > 0 the renderer must
   * offset the cursor by this amount or hide it if the live cursor row is
   * no longer visible.
   *
   * Width: `u32` — scrollback cap is 200 000 lines, well past
   * `u16::MAX` (65 535). The previous u16 saturated silently, so a
   * user scrolled past line 65 535 saw the offset frozen at 65 535
   * while alacritty's real offset kept growing. The renderer's
   * `FrameKey.displayOffset` was widened to UInt32 in b3edd7e to
   * defend against narrow-key wraparound, but the data was already
   * flat at the FFI boundary — that fix is only complete now that
   * the source field matches. Audit M5.
   */
  uint32_t display_offset;
  uint32_t mode;
  uintptr_t cells_len;
  const struct BBCell *cells;
  /**
   * Total lines currently retained in scrollback (grows as output flows
   * off-screen, capped at the scrollback limit). Used by the scroll
   * indicator to size its thumb proportional to total-buffer vs viewport.
   * Appended here to preserve the existing offsets of cells_len/cells.
   */
  uint32_t history_size;
  /**
   * DECSCUSR cursor shape: 0 = block, 1 = bar/beam, 2 = underline, 3 = hidden.
   * Sourced from `Term::cursor_style().shape` at snapshot time. Callers
   * render according to this; a value of 3 means the renderer should skip
   * drawing the cursor entirely.
   */
  uint8_t cursor_shape;
  uint8_t _pad2b[3];
};

/**
 * Owned UTF-8 byte buffer returned from text-extraction FFIs.
 *
 * `bytes`/`len` describe a read-only view into the heap buffer whose raw
 * parts are stored in `_owned_ptr` / `_owned_cap`. The Rust side
 * heap-allocates a `Box<BBString>`, builds the payload as a `Vec<u8>`, then
 * decomposes the vec (ptr + capacity) and installs the pointer into
 * `bytes`. Callers must free via `bb_string_release` exactly once; nothing
 * else keeps the backing allocation alive.
 *
 * The `_owned_*` fields are intentionally present in the C-visible layout
 * to keep the struct self-contained (one `Box<BBString>` + one `Vec<u8>`
 * buffer, freed together by `bb_string_release`). Consumers on the C side
 * should read only `bytes` and `len` and otherwise treat the struct as
 * opaque — never poke into the owned fields. Using raw pointer + capacity
 * instead of a literal `Vec<u8>` field lets cbindgen emit a complete,
 * FFI-safe layout that Swift can import: `Vec<u8>` is not `repr(C)`, so a
 * `Vec` field would surface as an incomplete type in the generated header.
 *
 * `_magic` is a sentinel set by `bb_string_new` (to `BB_STRING_MAGIC`) and
 * zeroed by `bb_string_release` before the heap buffer is reconstructed.
 * It gives `bb_string_release` a cheap defence against double-free and
 * wild-pointer input: a mismatching `_magic` short-circuits without
 * calling `Vec::from_raw_parts` (which would be UB on stale pointers).
 * Safety belt for Swift callers — still single-free by contract.
 */
struct BBString {
  const uint8_t *bytes;
  uintptr_t len;
  uint8_t *_owned_ptr;
  uintptr_t _owned_cap;
  /**
   * Magic sentinel: `BB_STRING_MAGIC` when live, `0` after release.
   * Double-free and wild-pointer input are rejected cheaply.
   */
  uint64_t _magic;
};

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Create a new terminal. Returns null on invalid input or internal error.
 *
 * # Thread safety
 * The returned handle is NOT Sync / Sendable. Once created, every subsequent
 * `bb_term_*` call on this handle MUST happen on the same thread; the handle
 * may never be accessed concurrently from two threads, even with external
 * locking. Crossing threads is undefined behavior. In Swift, restrict the
 * handle to the @MainActor or confine it to a single dedicated serial queue.
 * Debug builds latch the first accessor's ThreadId and debug_assert on
 * mismatch (rust-core-1 F2/F10).
 *
 * # Safety
 * The returned pointer must be freed exactly once via `bb_term_free`.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available yet to deliver a Fatal event).
 * The function returns null as the fallback value.
 *
 * # Clamping
 * `cols` and `rows` are clamped to `[MIN_DIM, MAX_DIM]` (currently `[2, 1000]`)
 * — symmetric with `bb_term_resize2`. A `0` on either axis still returns null
 * (treated as "no terminal requested"), matching pre-2026-04-29 behaviour.
 * `scrollback` is capped at `SCROLLBACK_MAX` (200 000 lines). Pre-H-7 a 1×1
 * grid was constructable and silently grew to 2×2 on the next resize; now
 * the clamp lands at construction time so the grid the caller observes via
 * snapshot matches what they asked for (modulo the public `[MIN_DIM, MAX_DIM]`
 * envelope).
 */
struct BBTerm *bb_term_new(uint16_t cols, uint16_t rows, uint32_t scrollback);

/**
 * Free a terminal handle created by `bb_term_new`.
 *
 * # Safety
 * `term` must have been returned by `bb_term_new` and not previously freed.
 * Passing null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no safe `BBTerm` context is available during teardown to deliver
 * a Fatal event). The function returns unit as the fallback value.
 */
void bb_term_free(struct BBTerm *term);

/**
 * Feed `len` bytes from `bytes` into the terminal's VT parser.
 *
 * # Safety
 * - `term` must be non-null, properly aligned (obtained from `bb_term_new`),
 *   and not freed for the duration of this call.
 * - `bytes` must be non-null when `len > 0` and point to a readable region of
 *   at least `len` bytes. Passing `bytes = null, len = 0` is safe (no-op).
 * - No two threads may call any `bb_term_*` function concurrently on the same
 *   `term`; interior state is mutated and `Term`/`Processor` are not `Sync`.
 * - `len` must be `<= isize::MAX as usize`. Larger values are rejected up
 *   front (no input processed) with a Fatal event dispatched — defense-in-
 *   depth against `slice::from_raw_parts`'s safety precondition (audit
 *   L-11). Swift's BBTerm wrapper can't construct such an input, but C-ABI
 *   consumers (fuzzers, native bindings, pre-Swift-conversion test harnesses)
 *   can.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_input(struct BBTerm *term, const uint8_t *bytes, uintptr_t len);

/**
 * Resize the terminal grid. Out-of-range (zero) dimensions are ignored.
 *
 * # Safety
 * `term` must be a valid non-null pointer from `bb_term_new`, properly
 * aligned, not freed for the duration of the call. No concurrent calls on
 * the same term.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 *
 * Callers that need to know whether the requested dimensions were clamped
 * should prefer `bb_term_resize2`, which returns the actually-applied dims
 * and a `clamped` flag. The void-returning form here is retained for ABI
 * stability; it internally delegates to the same clamp logic.
 */
void bb_term_resize(struct BBTerm *term, uint16_t cols, uint16_t rows);

/**
 * Resize the terminal grid and report the actually-applied dimensions.
 *
 * Dimensions are clamped to `[2, 1000]` on each axis to avoid the reflow
 * explosion on tiny grids and the 100+ GB allocation on huge grids
 * (documented in the floor/ceiling comment inside this function and in
 * `MEMORY`). Zero on either axis is a no-op and returns
 * `BBResizeResult { 0, 0, 0 }`.
 *
 * `clamped` is the signal to Swift that `TIOCSWINSZ` should be told the
 * APPLIED size, not the requested one — otherwise the shell and the grid
 * disagree about the viewport (rust-core-3 F4).
 *
 * # Safety
 * Same as `bb_term_resize`.
 */
struct BBResizeResult bb_term_resize2(struct BBTerm *term, uint16_t cols, uint16_t rows);

/**
 * Register (or clear) the event callback for a terminal.
 *
 * Pass `cb = None` to disable event delivery.  `ctx` is an opaque pointer
 * forwarded verbatim to every callback invocation; pass `null` if unused.
 *
 * # Safety
 * - `term` must be non-null, valid, and not freed while the callback is
 *   registered.
 * - `ctx` must remain valid for all subsequent `bb_term_input` calls until
 *   the callback is cleared or the terminal is freed.
 * - The callback may be invoked synchronously from within `bb_term_input`;
 *   it must not call any `bb_term_*` function on the same `term` handle
 *   (no re-entrant use).
 * - All access must occur on the same thread (no concurrent calls on the
 *   same term).
 * - Passing `term = null` is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_set_event_cb(struct BBTerm *term, void (*cb)(struct BBEvent, void*), void *ctx);

/**
 * Take an immutable snapshot of the current grid state.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Returns null on null input.
 * The returned pointer must be released by exactly one `bb_snap_release` per
 * successful call (plus one per `bb_snap_retain`).
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * null as the fallback value.
 */
const struct BBSnap *bb_term_take_snapshot(struct BBTerm *term);

/**
 * Increment refcount. Returns the input pointer for fluent usage.
 *
 * # Safety
 * `snap` must be a pointer returned by `bb_term_take_snapshot` or previously
 * retained, and not yet released to zero. Null is a no-op (returns null).
 * Safe to call from any thread.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns the input
 * `snap` pointer as the fallback value.
 */
const struct BBSnap *bb_snap_retain(const struct BBSnap *snap);

/**
 * Decrement refcount; free when it reaches zero.
 *
 * # Safety
 * Each `snap` must be released exactly once per acquire (new or retain).
 * Null is a no-op. Safe to call from any thread, but each concrete handle
 * follows the acquire/release discipline documented above.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns unit as
 * the fallback value.
 */
void bb_snap_release(const struct BBSnap *snap);

/**
 * Look up the OSC 8 link id at a snapshot cell. Returns 0 when `snap` is
 * null, `(row, col)` is outside the grid, or the cell has no OSC 8
 * attribution.
 *
 * Pass the returned non-zero id to `bb_snap_link_url` to get the URL.
 *
 * # Safety
 * `snap` must be non-null and returned by `bb_term_take_snapshot` /
 * `bb_snap_retain`, not yet released to zero.
 */
uint32_t bb_snap_link_id_at(const struct BBSnap *snap, uint16_t row, uint16_t col);

/**
 * Resolve an OSC 8 link id to its UTF-8 URL. Returns null when `snap` is
 * null, `link_id == 0`, or the id is unknown. The returned pointer is
 * valid for the snapshot's lifetime (until the matching `bb_snap_release`
 * drops the refcount to zero).
 *
 * # Safety
 * `snap` must be non-null and returned by `bb_term_take_snapshot` /
 * `bb_snap_retain`, not yet released to zero.
 */
const char *bb_snap_link_url(const struct BBSnap *snap, uint32_t link_id);

/**
 * Toggle OSC 10 / 11 / 12 `?` reply behaviour. Disabled by default so
 * a hostile remote can't round-trip the palette back into the PTY
 * (mitigates the zsh-vi-mode command-injection class). Pass `1` to
 * enable replies when running a known-safe shell that wants nvim /
 * tmux auto-theming.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null is a no-op.
 */
void bb_term_set_color_query_enabled(struct BBTerm *term, uint8_t enabled);

/**
 * Read the current terminal mode bitfield as a `bb_mode::*` union.
 * O(1) — no snapshot allocation. Use when a caller needs to branch on
 * a single mode bit (e.g., focus-event emission must check
 * `FOCUS_IN_OUT` before writing `\x1b[I` / `\x1b[O` to the PTY, since
 * emitting those bytes when the TUI hasn't enabled mode 1004 would be
 * interpreted as `HPA` / a cursor move).
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null returns 0 (no bits set),
 * which is the correct default for "don't emit".
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * 0 as the fallback value.
 */
uint32_t bb_term_current_mode(struct BBTerm *term);

/**
 * Report whether the snapshot's damage set is "full" (all rows need a
 * redraw — scroll, insert-mode, viewport scrollback change). When true,
 * the renderer must treat every row as damaged regardless of
 * `bb_snap_damage_rows`.
 *
 * # Safety
 * `snap` must be a pointer from `bb_term_take_snapshot` or retained from
 * one. Null returns 1 (the safe default: repaint everything).
 */
uint8_t bb_snap_damage_is_full(const struct BBSnap *snap);

/**
 * Copy the snapshot's damaged-row indices into the caller's buffer. Returns
 * the TOTAL number of damaged rows (which may exceed `out_cap`); the
 * function writes at most `min(total, out_cap)` rows into `out`.
 *
 * Truncation detection: callers compare the return value against `out_cap`.
 * If `return_value > out_cap`, the buffer was too small and the caller
 * should re-allocate at `return_value` slots and retry to avoid leaving
 * stale pixels on the undrawn rows.
 *
 * Length probe: passing `out = null` with any `out_cap` returns the
 * total count without writing anything, so a caller can size a buffer
 * before allocating.
 *
 * If the damage is `Full`, returns 0 — callers must check
 * `bb_snap_damage_is_full` first and treat "full" as "all rows need
 * redraw" regardless of this function's return value.
 *
 * # Safety
 * - `snap` must be a pointer from `bb_term_take_snapshot` or retained
 * - `out` must either be null OR point to at least `out_cap * 2` bytes of
 *   writable memory. No u16 alignment is required on `out` — the body
 *   copies byte-wise (rust-core-4 F3).
 * - Safe to call from any thread.
 */
uintptr_t bb_snap_damage_rows(const struct BBSnap *snap, uint16_t *out, uintptr_t out_cap);

/**
 * Scroll the display by `delta` lines. Positive = scroll up (show older
 * content), negative = scroll down (show newer content, towards bottom).
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Passing null or delta == 0 is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_scroll(struct BBTerm *term, int32_t delta);

/**
 * Snap the viewport back to the live grid (display_offset = 0). Called after
 * any user keystroke so typing/Enter always brings them back from scrollback
 * history. A no-op if already at the bottom.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * unit as the fallback value.
 */
void bb_term_scroll_to_bottom(struct BBTerm *term);

/**
 * Clear the visible screen AND the scrollback, moving the cursor to the
 * top-left. Equivalent to `clear -x` (BSD) / iTerm2's "⌘K" wipe — NOT
 * what `clear(1)` emits, which is viewport-only (a plain `\x1b[H\x1b[2J`
 * that leaves scrollback intact). The terminal palette is intentionally
 * preserved (the user's theme survives ⌘K). All other parser / rate-
 * limiter / cache state IS reset so a pre-clear adversarial flood
 * can't degrade the post-clear session — see audit H-3 (2026-04-29).
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null is a no-op.
 */
void bb_term_clear_all(struct BBTerm *term);

/**
 * Update one slot of the terminal's color palette. Slot indices match
 * alacritty's `NamedColor` ordering: 0..=15 = 16 ANSI colors, 16..=255 =
 * extended 256-palette, 256 = Foreground, 257 = Background, 258 = Cursor,
 * 259 = BrightForeground, plus a few more (see alacritty's NamedColor enum).
 * `rgb` is packed 0xRRGGBB.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Null `term` is a no-op. Slots
 * beyond alacritty's palette length are silently ignored.
 */
void bb_term_set_named_color(struct BBTerm *term, uint16_t slot, uint32_t rgb);

/**
 * Extract UTF-8 text from the terminal buffer between two buffer-relative
 * points. `start_line`/`end_line` are grid lines where 0 is the top of the
 * visible viewport and negative values reach into scrollback (buffer-relative,
 * matching alacritty's `Line(i32)` convention).
 *
 * `rect == 0` selects prose mode: the first line is emitted from `start_col`
 * to the end of the row, the last line from column 0 to `end_col`, and
 * middle lines are taken in full. Trailing spaces are trimmed from every
 * line except the last to avoid pulling the grid's blank fill into copied
 * output.
 *
 * `rect != 0` selects rectangular mode: every line is clipped to
 * `[start_col, end_col]` with no trimming.
 *
 * `\0` cells (alacritty's "unrendered" sentinel) are emitted as spaces. Real
 * spaces come through as-is. Wide-char spacer cells (alacritty's
 * `WIDE_CHAR_SPACER` / `LEADING_WIDE_CHAR_SPACER` flags) are SKIPPED entirely
 * — the preceding primary cell already held the wide glyph's character, and
 * emitting a space for the spacer would double-count columns and break paste
 * round-trip for CJK/emoji (e.g. "中文" would emit as "中 文 "). Lines outside
 * `[topmost_line, bottommost_line]` are skipped silently. Points are
 * normalized so `(start_line, start_col) <= (end_line, end_col)` before
 * iterating.
 *
 * Returns a heap-allocated `BBString` the caller must free with
 * `bb_string_release`. Returns null when `term` is null.
 *
 * # Safety
 * Same preconditions as `bb_term_input`. Caller owns the returned pointer.
 *
 * Panics inside this function are caught by `catch_unwind` and delivered as a
 * `BBEventKind::Fatal` event to the registered callback. The function returns
 * null as the fallback value.
 */
struct BBString *bb_term_text_range(struct BBTerm *term,
                                    int32_t start_line,
                                    uint16_t start_col,
                                    int32_t end_line,
                                    uint16_t end_col,
                                    uint8_t rect);

/**
 * Free a `BBString` returned by `bb_term_text_range`.
 *
 * Rebuilds the owned `Vec<u8>` from `_owned_ptr`/`_owned_cap`/`len` so its
 * heap buffer is deallocated with the matching `Vec` allocator, then drops
 * the `Box<BBString>`.
 *
 * Defends against double-free and wild-pointer input by checking
 * `_magic` against `BB_STRING_MAGIC` before touching the owned parts. A
 * mismatching magic returns early (with a one-line log) without calling
 * `Vec::from_raw_parts` — that would be UB on stale/invalid raw parts and
 * the null guard can't catch it. Successful releases zero the magic so a
 * subsequent double-release is detected cheaply.
 *
 * # Safety
 * `s` must have been returned by `bb_term_text_range` and not previously
 * released. Passing null is a no-op.
 *
 * Panics inside this function are caught by `catch_unwind` and swallowed
 * silently (no `BBTerm` context is available). The function returns unit as
 * the fallback value.
 */
void bb_string_release(struct BBString *s);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* BLACKBIRD_CORE_H */
