import Foundation
import BBCore
import os

/// Swift wrapper over the BBCore C ABI. Owns a single BBTerm and guarantees
/// freeing on deinit. Not Sendable — must be used from a single serial queue
/// (the `core` queue in a TerminalSession).
public final class BBTerm {
    /// Floor on resize / construction dimensions. Mirrors
    /// `MIN_DIM` in `core/src/lib.rs`. Wrapper-side clamping lets the
    /// public `BBTerm.resize(to:)` accept anything callers throw at
    /// it — including the legacy `(0, 0)` shape — without trapping
    /// (audit L-18 / EC-7). The Rust side enforces the same floor;
    /// this constant exists so the wrapper can normalise BEFORE the
    /// FFI call so the returned dimensions always describe a usable
    /// grid.
    public static let MIN_DIM: UInt16 = 2
    /// Ceiling counterpart to `MIN_DIM`. Same rationale: wrapper-side
    /// clamp matches the Rust `MAX_DIM` so callers see a usable
    /// `Size` echoed back.
    public static let MAX_DIM: UInt16 = 1000

    /// Re-entrancy latch set while `dispatch(_:)` is running the
    /// registered event handler. Used by the precondition in
    /// `dispatch` to catch any handler that synchronously calls back
    /// into a `bb_term_*` function — alacritty's `&mut Term` borrow
    /// would be live while we re-enter, which is UB-adjacent. Audit
    /// M-9 (2026-04-29) promoted this from a `#if DEBUG`-only field
    /// to a Release-also field: the cost of one Bool branch per
    /// dispatched event is negligible compared to the cost of UB
    /// silently corrupting alacritty state in Release.
    fileprivate var isInsideEventDispatch: Bool = false

    /// Shared diagnostic channel for defensive guards in BBTerm /
    /// BBSnapshot — sibling of M-15 / L-17 / M-17 (one-shot warning
    /// when a clamp engages). Gives the dim-clamp and
    /// `rowTextWithUTF16ToColMap` `.invalid` branch a discoverable
    /// breadcrumb in `log stream --predicate 'category == "bbterm"'`
    /// without flooding when the regression is sustained.
    fileprivate static let clampLogger = Logger(
        subsystem: "dev.conjfrnk.blackbird",
        category: "bbterm"
    )
    /// One-shot latch: fires the dim-clamp warning at most once per
    /// process. Audit follow-up (2026-04-29).
    fileprivate static let didLogDimClamp = OSAllocatedUnfairLock(initialState: false)
    /// One-shot latch for `rowTextWithUTF16ToColMap` `.invalid` branch.
    /// Audit L-15 / DI-9 follow-up (2026-04-29).
    fileprivate static let didLogInvalidCell = OSAllocatedUnfairLock(initialState: false)

    public struct Size: Equatable {
        public var cols: UInt16
        public var rows: UInt16
        public init(cols: UInt16, rows: UInt16) {
            self.cols = cols
            self.rows = rows
        }
    }

    public enum Event {
        case title(String)
        case bell
        case cursorShape(Int)
        case osc52Clipboard(String)
        /// Bytes to write back to the PTY (terminal → shell). Generated by
        /// the VT parser in response to DSR, DA1/DA2, and similar queries.
        case ptyWrite(Data)
        /// Shell-emitted working-directory change via OSC 7. Payload is a
        /// decoded, local filesystem path (no `file://` prefix). Fires only
        /// when the Rust core validates scheme == file and host in {empty,
        /// localhost}; matches spec §4.1.
        case cwdChanged(String)
        /// Shell-emitted OSC 133 prompt/command mark. `kind` is one of
        /// A/B/C/D (prompt start / command start / command output /
        /// command end). `exitCode` is populated only for kind D; empty
        /// string otherwise.
        case promptMark(kind: PromptMarkKind, exitCode: String)
        case fatal(String)
    }

    /// OSC 133 sub-kinds — see BBPromptMarkKind in core/src/lib.rs.
    public enum PromptMarkKind: UInt8 {
        case promptStart = 1
        case commandStart = 2
        case commandOutput = 3
        case commandEnd = 4
    }

    public typealias EventHandler = (Event) -> Void

    // 'struct BBTerm' is an opaque forward declaration in BBCore.h;
    // Swift imports struct BBTerm * as OpaquePointer throughout.
    private var handle: OpaquePointer?
    private var handler: EventHandler?
    private let ctxBox: UnsafeMutablePointer<EventCtx>

    private final class EventCtx {
        weak var owner: BBTerm?
    }

    public init?(size: Size, scrollback: UInt32 = 100_000) {
        // 100k lines covers dense Claude Code / build-log / `cargo
        // build` sessions without users needing to think about the cap.
        // Alacritty's scrollback is lazily allocated, so a fresh BBTerm
        // with scrollback=100_000 uses the same memory as one with
        // scrollback=10_000 — the extra headroom only materialises when
        // output actually scrolls off. Capped at 200k by the Rust side
        // (see bb_term_new).
        //
        // Wrapper-side clamp matches the Rust core's `[MIN_DIM, MAX_DIM]`
        // envelope so a single source-of-truth defines the legitimate
        // grid range for both layers. The Rust side independently clamps
        // (belt-and-braces). Audit follow-up (2026-04-29): when the clamp
        // engages, fire a one-shot warning so a callsite feeding
        // garbage dims is discoverable in `log stream` rather than
        // silently observing a snapshot whose dims don't match what
        // they asked for.
        let clampedCols = min(max(size.cols, Self.MIN_DIM), Self.MAX_DIM)
        let clampedRows = min(max(size.rows, Self.MIN_DIM), Self.MAX_DIM)
        if clampedCols != size.cols || clampedRows != size.rows {
            Self.didLogDimClamp.withLock { logged in
                if !logged {
                    logged = true
                    Self.clampLogger.warning("dim clamp engaged in BBTerm.init: requested=(\(size.cols, privacy: .public),\(size.rows, privacy: .public)) clamped=(\(clampedCols, privacy: .public),\(clampedRows, privacy: .public)) bounds=[\(Self.MIN_DIM, privacy: .public),\(Self.MAX_DIM, privacy: .public)]")
                }
            }
        }
        guard let ptr = bb_term_new(clampedCols, clampedRows, scrollback) else { return nil }
        self.handle = ptr

        let box = UnsafeMutablePointer<EventCtx>.allocate(capacity: 1)
        box.initialize(to: EventCtx())
        self.ctxBox = box

        // Set the weak back-reference after self is fully initialized.
        box.pointee.owner = self
        bb_term_set_event_cb(ptr, BBTerm.eventTrampoline, UnsafeMutableRawPointer(box))
    }

    /// Tear down the Rust core handle and clear the trampoline. Must
    /// be called on the same serial queue that drives `bb_term_input`
    /// — otherwise an in-flight trampoline on the input queue races
    /// the FFI clear/free here. Idempotent; subsequent calls are
    /// no-ops.
    ///
    /// Production callers (TerminalSession.terminate) wrap this in
    /// `coreQueue.sync` so the same-queue contract is satisfied.
    /// `deinit` falls back to calling this if the explicit path
    /// didn't fire — that fallback is the historical path; the
    /// explicit hook lets `deinit` become a no-op for the FFI portion
    /// when an owner properly tears down through `terminate()`. Audit
    /// M6.
    public func terminate() {
        guard let h = handle else { return }
        // Clear the trampoline's back-reference BEFORE the FFI free
        // so any straggler trampoline call (which only happens off
        // the contract — same-queue discipline forbids it — but we
        // defend anyway) reads a nil owner and short-circuits before
        // touching `self`.
        ctxBox.pointee.owner = nil
        bb_term_set_event_cb(h, nil, nil)
        bb_term_free(h)
        handle = nil
    }

    deinit {
        // If the owner already called `terminate()` on the right
        // queue, `handle` is nil and this is a clean no-op. Otherwise
        // we run the FFI teardown here as a fallback — same race
        // surface as pre-M6, but the explicit-terminate path now
        // exists for owners who want to be deterministic about which
        // queue runs the free.
        //
        // Audit M-8 (2026-04-29): the FFI contract requires every
        // `bb_term_*` call (including the trampoline-clear and free
        // here) to happen on the same thread context that has been
        // driving `bb_term_input`. Production paths
        // (TerminalSession.terminate) ensure this by calling
        // `terminate()` on `coreQueue.sync` first; deinit then
        // observes `handle == nil`. A runtime thread-equality check
        // here would false-positive on legitimate same-queue use
        // because GCD's `dispatch_sync` optimisation can borrow the
        // calling thread — the queue's worker pthread isn't a
        // stable identity. Contract enforcement therefore lives in
        // `TerminalSession`'s dispatchPrecondition tripwires (audit
        // M-12); the BBTerm wrapper trusts callers to honour the
        // single-thread discipline. M-8 remains a doc-only fix at
        // this layer pending a queue-aware enforcement primitive
        // (e.g. `dispatchPrecondition(.onQueue(owningQueue))` if
        // BBTerm grew an explicit `owningQueue` field).
        if let h = handle {
            ctxBox.pointee.owner = nil
            bb_term_set_event_cb(h, nil, nil)
            bb_term_free(h)
        }
        ctxBox.deinitialize(count: 1)
        ctxBox.deallocate()
    }

    public func onEvent(_ handler: @escaping EventHandler) {
        self.handler = handler
    }

    public func input(_ bytes: [UInt8]) {
        guard let h = handle else { return }
        bytes.withUnsafeBufferPointer { buf in
            bb_term_input(h, buf.baseAddress, UInt(buf.count))
        }
    }

    public func input(_ string: String) {
        input(Array(string.utf8))
    }

    /// Resize the grid to `size`, returning the dimensions actually applied
    /// after the `[MIN_DIM, MAX_DIM]` clamp on each axis. Callers that
    /// drive a PTY's `TIOCSWINSZ` MUST use the returned dims, not the
    /// requested ones — telling the shell it has 1500 columns when the grid
    /// only has 1000 makes the shell wrap text past the visible viewport
    /// (rust-core-3 F4 / Bug #3).
    ///
    /// Audit L-18 / EC-7 (2026-04-29): the wrapper now clamps to
    /// `[MIN_DIM, MAX_DIM]` BEFORE calling the FFI so a `(0, 0)` request
    /// no longer trap-aborts the process — it floors to `(MIN_DIM,
    /// MIN_DIM)`. The Rust side independently clamps, so this is
    /// belt-and-braces; the wrapper-side clamp lets `BBTerm.resize` be
    /// safely called from any code path that hasn't pre-validated dims
    /// (e.g., a future state-restoration with a stale persisted size).
    /// A DEBUG `assertionFailure` still fires on a zero input so legacy
    /// callers that were relying on the old precondition catch the drift
    /// during development.
    @discardableResult
    public func resize(to size: Size) -> Size {
        #if DEBUG
        if size.cols == 0 || size.rows == 0 {
            assertionFailure(
                "BBTerm.resize received zero dimension; got cols=\(size.cols), rows=\(size.rows). "
                + "Wrapper clamps up to MIN_DIM=\(Self.MIN_DIM) so this no longer traps in Release, "
                + "but the call site is feeding garbage — fix it."
            )
        }
        #endif
        let clampedCols = min(max(size.cols, Self.MIN_DIM), Self.MAX_DIM)
        let clampedRows = min(max(size.rows, Self.MIN_DIM), Self.MAX_DIM)
        if clampedCols != size.cols || clampedRows != size.rows {
            // Audit follow-up (2026-04-29): one-shot warning when the
            // wrapper-side clamp engages. Sibling of M-15 / L-17 / M-17.
            // Shares the latch with `init?(size:)` so a noisy caller
            // doesn't get two warning lines for "same broken value
            // construct + resize".
            Self.didLogDimClamp.withLock { logged in
                if !logged {
                    logged = true
                    Self.clampLogger.warning("dim clamp engaged in BBTerm.resize: requested=(\(size.cols, privacy: .public),\(size.rows, privacy: .public)) clamped=(\(clampedCols, privacy: .public),\(clampedRows, privacy: .public)) bounds=[\(Self.MIN_DIM, privacy: .public),\(Self.MAX_DIM, privacy: .public)]")
                }
            }
        }
        guard let h = handle else { return Size(cols: clampedCols, rows: clampedRows) }
        let result = bb_term_resize2(h, clampedCols, clampedRows)
        // The wrapper-side clamp guarantees a non-zero (cols, rows) reach
        // the FFI, so a `(0, 0, 0)` return now exclusively signals the
        // null-handle / panic fallback path. Fall through to returning
        // the clamped request, which itself describes a usable grid.
        if result.applied_cols == 0 || result.applied_rows == 0 {
            return Size(cols: clampedCols, rows: clampedRows)
        }
        return Size(cols: result.applied_cols, rows: result.applied_rows)
    }

    public func scroll(delta: Int32) {
        guard let h = handle else { return }
        bb_term_scroll(h, delta)
    }

    /// Current terminal mode bitfield. Lightweight — no snapshot allocation.
    /// Use when a caller needs to branch on a single bit between snapshot
    /// cycles (the focus-event path is the motivating case: we must check
    /// `FOCUS_IN_OUT` at the moment the window's focus changes, not whatever
    /// mode the last-rendered snapshot captured).
    public var currentMode: BBTermMode {
        guard let h = handle else { return [] }
        return BBTermMode(rawValue: bb_term_current_mode(h))
    }

    /// Compute the focus-event escape for the given focus state, gated on
    /// mode 1004 being active. Returns `nil` when the TUI hasn't requested
    /// focus events — sending those bytes unconditionally would be
    /// interpreted as `HPA` and move the cursor.
    ///
    /// Per xterm focus-events doc: `\x1b[I` on gain, `\x1b[O` on loss. The
    /// caller is responsible for routing the returned bytes to the PTY.
    public func focusChangeBytes(focused: Bool) -> Data? {
        guard currentMode.contains(.focusInOut) else { return nil }
        return focused ? Data([0x1b, 0x5b, 0x49]) : Data([0x1b, 0x5b, 0x4f])
    }

    /// Snap the viewport back to the live grid. Called after any keystroke so
    /// typing always brings the user out of scrollback.
    public func scrollToBottom() {
        guard let h = handle else { return }
        bb_term_scroll_to_bottom(h)
    }

    public func clearAll() {
        guard let h = handle else { return }
        bb_term_clear_all(h)
    }

    /// Update one palette slot. See BBCore.h for slot conventions.
    public func setColor(slot: Int, rgb: UInt32) {
        guard let h = handle else { return }
        bb_term_set_named_color(h, UInt16(slot), rgb)
    }

    /// Enable or disable OSC 10 / 11 / 12 `?` reply behaviour. Off by
    /// default so a hostile remote can't round-trip the palette back into
    /// the PTY (mitigates the zsh-vi-mode command-injection class). Users
    /// who want Neovim / tmux auto-theming on a modern shell can opt in
    /// via Preferences — see `Preferences.shared.colorQueryEnabled`.
    public func setColorQueryEnabled(_ enabled: Bool) {
        guard let h = handle else { return }
        bb_term_set_color_query_enabled(h, enabled ? 1 : 0)
    }

    /// Extract UTF-8 text between two buffer points. `rectangular` selects
    /// the axis-aligned bounding box between start/end; `false` selects the
    /// prose-style sweep (first line from startCol, middle lines full, last
    /// line to endCol). Lines outside the buffer are silently skipped.
    ///
    /// Returns `nil` on (a) null handle, (b) zero-area range (FFI returns
    /// an empty `BBString` and we forward `""`; an outright `nil` here is
    /// the C-side null-allocation fallback), or (c) a panic during text
    /// extraction (the Rust side catches it via `catch_unwind` and returns
    /// null, with a Fatal event also dispatched on the registered
    /// callback). Callers cannot distinguish (a) vs (c) from this return
    /// value alone — wire a `.fatal` handler via `onEvent` if you need to
    /// learn about extraction-time panics. Audit L-9 (2026-04-29).
    public func textRange(
        startLine: Int32, startCol: Int,
        endLine: Int32,   endCol: Int,
        rectangular: Bool
    ) -> String? {
        guard let h = handle else { return nil }
        // `UInt16(col)` traps on negative or > 65535. Selection cols
        // ought to stay in [0, grid.cols-1] ≤ 999, but a scrollback-
        // based selection with `col = -1` (or a caller passing
        // unclamped BufferPoint.col) would otherwise abort. Saturate
        // at the cast; Rust side clamps again against the grid edge.
        guard let raw = bb_term_text_range(
            h,
            startLine, UInt16(clamping: startCol),
            endLine,   UInt16(clamping: endCol),
            rectangular ? 1 : 0
        ) else {
            return nil
        }
        defer { bb_string_release(raw) }
        let buf = UnsafeBufferPointer(start: raw.pointee.bytes, count: Int(raw.pointee.len))
        return String(decoding: buf, as: UTF8.self)
    }

    public func snapshot() -> BBSnapshot? {
        guard let h = handle else { return nil }
        guard let raw = bb_term_take_snapshot(h) else { return nil }
        return BBSnapshot(retaining: raw)
    }

    // MARK: - Event trampoline

    private static let eventTrampoline: @convention(c) (BBEvent, UnsafeMutableRawPointer?) -> Void = { ev, ctx in
        guard let ctx else { return }
        let box = ctx.assumingMemoryBound(to: EventCtx.self)
        guard let owner = box.pointee.owner else { return }
        owner.dispatch(ev)
    }

    private func dispatch(_ ev: BBEvent) {
        guard let handler else { return }
        // Re-entrancy guard: if the event handler calls back into a
        // `bb_term_*` function while we're still inside a dispatch, the
        // Rust core may re-enter alacritty's `&mut Term` while the prior
        // call is still holding it. That's UB-adjacent — the borrow
        // checker can't see across the FFI boundary. Audit ffi-bridge
        // F11 / M-9 (2026-04-29).
        //
        // M-9 promoted this from a `#if DEBUG` `assertionFailure` to a
        // Release-also `precondition`: aborting loudly is strictly
        // better than corrupting alacritty state, and the cost is one
        // Bool branch on a low-volume code path. The Rust side catches
        // many but not all re-entry shapes via `FFI_FATAL_IN_FLIGHT`;
        // this Swift guard is the static catch for the call-graph
        // shape ("handler synchronously calls bb_term_*"), the Rust
        // guard is the dynamic catch for the data shape (panic during
        // a callback chain).
        precondition(
            !isInsideEventDispatch,
            "BBTerm event handler called back into bb_term_* synchronously. "
            + "Route the call through DispatchQueue.main.async or a later "
            + "runloop tick instead. Audit M-9."
        )
        isInsideEventDispatch = true
        defer { isInsideEventDispatch = false }
        // BBEventKind is typedef uint32_t in C. ev.kind is UInt32.
        // The BB_EVENT_KIND_* constants are C enum variants; use their integer
        // values directly to avoid Swift 6 cross-module typedef comparison issues.
        switch ev.kind {
        case 1:   // BB_EVENT_KIND_TITLE
            handler(.title(Self.string(from: ev)))
        case 2:   // BB_EVENT_KIND_BELL
            handler(.bell)
        case 3:   // BB_EVENT_KIND_CURSOR_SHAPE
            handler(.cursorShape(Int(ev.i32_arg)))
        case 4:   // BB_EVENT_KIND_OSC52_CLIPBOARD
            handler(.osc52Clipboard(Self.string(from: ev)))
        case 5:   // BB_EVENT_KIND_PTY_WRITE
            handler(.ptyWrite(Self.data(from: ev)))
        case 6:   // BB_EVENT_KIND_CWD_CHANGED
            handler(.cwdChanged(Self.string(from: ev)))
        case 7:   // BB_EVENT_KIND_PROMPT_MARK
            if let kind = PromptMarkKind(rawValue: UInt8(clamping: ev.i32_arg)) {
                handler(.promptMark(kind: kind, exitCode: Self.string(from: ev)))
            } else {
                // Audit L-3 (2026-04-29): the Rust side defines exactly
                // the four `PromptMarkKind` raw values 1..=4. A value
                // outside that range here means the C ABI drifted
                // (Rust added a new variant the Swift enum doesn't
                // know about, or `i32_arg` got mis-encoded). Drop in
                // Release; loud-fail in DEBUG so CI catches drift.
                assertionFailure(
                    "BB_EVENT_KIND_PROMPT_MARK with unknown raw value \(ev.i32_arg). "
                    + "Swift PromptMarkKind covers 1..=4; Rust ABI has drifted. Audit L-3."
                )
            }
        case 99:  // BB_EVENT_KIND_FATAL
            handler(.fatal(Self.string(from: ev)))
        default:
            // Audit L-3 (2026-04-29): unknown event kind means the
            // Rust enum gained a variant the Swift switch doesn't
            // handle. Silent drop in Release (forward-compatible),
            // loud-fail in DEBUG so the regression surfaces in CI on
            // the next FFI bump.
            assertionFailure(
                "BBTerm.dispatch saw unknown BBEventKind raw value \(ev.kind). "
                + "Swift switch covers 1..7 + 99; Rust ABI has drifted. Audit L-3."
            )
        }
    }

    private static func string(from ev: BBEvent) -> String {
        guard let ptr = ev.payload, ev.len > 0 else { return "" }
        let buf = UnsafeBufferPointer(start: ptr, count: Int(ev.len))
        return String(decoding: buf, as: UTF8.self)
    }

    private static func data(from ev: BBEvent) -> Data {
        guard let ptr = ev.payload, ev.len > 0 else { return Data() }
        return Data(bytes: ptr, count: Int(ev.len))
    }
}

/// Terminal mode flags mirrored from the Rust `bb_mode` constants.
/// Bits correspond 1-to-1 with the `BBSnap.mode` field.
public struct BBTermMode: OptionSet {
    public let rawValue: UInt32
    public init(rawValue: UInt32) { self.rawValue = rawValue }

    public static let altScreen        = BBTermMode(rawValue: 1 << 0)
    public static let appCursor        = BBTermMode(rawValue: 1 << 1)
    public static let appKeypad        = BBTermMode(rawValue: 1 << 2)
    public static let bracketedPaste   = BBTermMode(rawValue: 1 << 3)
    public static let mouseReportClick = BBTermMode(rawValue: 1 << 4)
    public static let mouseMotion      = BBTermMode(rawValue: 1 << 5)
    public static let mouseDrag        = BBTermMode(rawValue: 1 << 6)
    public static let sgrMouse         = BBTermMode(rawValue: 1 << 7)
    public static let focusInOut       = BBTermMode(rawValue: 1 << 8)
    public static let showCursor       = BBTermMode(rawValue: 1 << 9)
    public static let lineWrap         = BBTermMode(rawValue: 1 << 10)
    // Kitty keyboard protocol. When `disambiguateEscCodes` is set, the encoder
    // must emit CSI u sequences for modified keys so TUIs can distinguish
    // Shift+Enter from Enter, Ctrl+i from Tab, etc.
    public static let disambiguateEscCodes = BBTermMode(rawValue: 1 << 11)
    public static let reportEventTypes     = BBTermMode(rawValue: 1 << 12)
    public static let reportAlternateKeys  = BBTermMode(rawValue: 1 << 13)
    public static let reportAllKeysAsEsc   = BBTermMode(rawValue: 1 << 14)
    public static let reportAssociatedText = BBTermMode(rawValue: 1 << 15)
    /// xterm `modifyOtherKeys` level ≥ 1. Set when the TUI pushes
    /// `CSI > 4 ; 1 m` or `CSI > 4 ; 2 m`. The encoder emits
    /// `CSI 27 ; <mod> ; <cp> ~` for modified printables + control-code
    /// colliders (Tab / Enter / Esc / Backspace) so Emacs-family
    /// programs receive unambiguous bytes for keys like Ctrl+. /
    /// Ctrl+, / Shift+Return that the legacy encoding can't express.
    /// Kitty protocol flags take precedence when any Kitty bit is set.
    public static let modifyOtherKeys = BBTermMode(rawValue: 1 << 16)
}

/// Immutable snapshot of the grid. Holds a ref until deinit.
public final class BBSnapshot {
    private let handle: UnsafePointer<BBSnap>

    /// Monotonic sequence id assigned once at init. Every new `BBSnapshot`
    /// gets a strictly larger number than any previously-allocated one.
    /// Used by `MetalRenderer.FrameKey` as a dedup token that — unlike the
    /// raw handle pointer — survives allocator address reuse: an old
    /// snapshot's handle can be freed and a new snapshot's handle can
    /// land at the same address, which would make a pointer-equality
    /// cache skip a legitimate repaint (see comments there).
    public let sequenceID: UInt64
    /// Private atomic counter. Using a static OSAtomic-style increment
    /// via `OSAtomicIncrement64` was considered, but a lock-guarded
    /// UInt64 is plenty given BBSnapshot init happens a few hundred
    /// times per second at most.
    private static let sequenceLock = NSLock()
    private static var nextSequenceID: UInt64 = 0
    private static func allocateSequence() -> UInt64 {
        sequenceLock.lock()
        nextSequenceID &+= 1
        let id = nextSequenceID
        sequenceLock.unlock()
        return id
    }

    init(retaining raw: UnsafePointer<BBSnap>) {
        self.handle = raw
        self.sequenceID = Self.allocateSequence()
    }

    deinit {
        bb_snap_release(handle)
    }

    public var cols: Int { Int(handle.pointee.cols) }
    public var rows: Int { Int(handle.pointee.rows) }
    public var cursorCol: Int { Int(handle.pointee.cursor_col) }
    public var cursorRow: Int { Int(handle.pointee.cursor_row) }
    public var cursorVisible: Bool { handle.pointee.cursor_visible != 0 }
    /// Lines scrolled above the live grid. 0 = pinned to bottom.
    public var displayOffset: Int { Int(handle.pointee.display_offset) }
    /// Total scrollback lines retained (up to the scrollback limit).
    public var historySize: Int { Int(handle.pointee.history_size) }
    /// DECSCUSR cursor shape: 0 = block, 1 = bar/beam, 2 = underline, 3 = hidden.
    public var cursorShape: Int { Int(handle.pointee.cursor_shape) }
    public var mode: UInt32 { handle.pointee.mode }
    public var termMode: BBTermMode { BBTermMode(rawValue: mode) }

    /// Four-way classification of a single cell. `character(at:row:)`
    /// collapses spacer / empty / invalid into one nil — fine for "give
    /// me what to render here" but ambiguous for layout math: a wide
    /// CJK glyph at col 0 paints col 1 as a spacer (an extension of
    /// the char on its left), whereas an unwritten cell at col 5 is
    /// empty (no glyph, no extension). Find / replace need to
    /// distinguish the two when computing column spans and DEL counts.
    public enum CellKind: Equatable {
        /// Cell carries a printable character. The leading cell of a
        /// wide glyph reports `.character`; the spacer cell to its
        /// right reports `.spacer`.
        case character(Character)
        /// Cell is a wide-glyph spacer — owned by the leading cell to
        /// its left (`WIDE_CHAR_SPACER`) or to its right at end-of-line
        /// (`LEADING_WIDE_CHAR_SPACER`).
        case spacer
        /// Cell has never been written by the shell — alacritty's
        /// `\0` sentinel.
        case empty
        /// Cell holds a non-zero scalar that fails `Unicode.Scalar`
        /// construction — surrogate scalars (`0xD800..=0xDFFF`),
        /// out-of-range values (≥ `0x110000`), or future invalid
        /// shapes the Rust core didn't filter. Treated by row-walkers
        /// as "skip without halting" so the row's haystack isn't
        /// truncated mid-line. alacritty 0.26 rejects surrogate
        /// scalars upstream so this is defensive today; if a future
        /// upstream change lets one through, the row-walker
        /// continues past it. Audit L-15 / DI-9 (2026-04-29).
        case invalid
    }

    /// Classify the cell at `(col, row)` for layout-math purposes. Used
    /// by the row-walker to compute exact wide-glyph widths and by the
    /// replace path to count shell-input characters in a match span.
    public func cellKind(at col: Int, row: Int) -> CellKind {
        guard col >= 0, row >= 0, col < cols, row < rows else { return .empty }
        // Audit L-19 / EC-9 (2026-04-29): defence-in-depth on
        // `row * cols + col`. Today bounded by the upstream guards
        // (`row < rows`, `col < cols` with rows/cols ≤ 1000), so
        // overflow is unreachable in practice. Promote to an explicit
        // overflow-aware compute so any future code path that calls
        // this with larger `Int` inputs can't silently wrap.
        guard let idx = Self.flatIndex(row: row, col: col, cols: cols) else { return .empty }
        guard idx < cellCount else { return .empty }
        let cell = handle.pointee.cells[idx]
        let spacerMask = UInt16(WIDE_CHAR_SPACER) | UInt16(LEADING_WIDE_CHAR_SPACER)
        if cell.flags & spacerMask != 0 {
            return .spacer
        }
        let scalar = cell.ch
        guard scalar != 0 else { return .empty }
        guard let us = Unicode.Scalar(scalar) else { return .invalid }
        return .character(Character(us))
    }

    /// Compute `row * cols + col` with overflow detection. Returns
    /// `nil` when either the multiply or the add would wrap a signed
    /// `Int`. Defence-in-depth helper for cell-array indexing
    /// (audit L-19 / EC-9, 2026-04-29). Today the inputs are bounded
    /// by `MAX_DIM` and overflow is unreachable; the helper exists so
    /// any future caller that lifts those bounds gets a safe fallback
    /// instead of a UB-adjacent wrap.
    fileprivate static func flatIndex(row: Int, col: Int, cols: Int) -> Int? {
        let (product, mulOverflow) = row.multipliedReportingOverflow(by: cols)
        if mulOverflow { return nil }
        let (idx, addOverflow) = product.addingReportingOverflow(col)
        if addOverflow { return nil }
        return idx
    }

    /// Walk a screen row's cells, skipping spacer cells, and return the
    /// row's visible characters together with a parallel UTF-16 →
    /// starting-column map. Used by find / replace to translate regex
    /// `NSRange` (UTF-16 units) and `String.range(of:)` results back to
    /// grid-cell columns. Without this map a wide CJK glyph (1 char, 2
    /// cells) or a non-BMP scalar (2 UTF-16 units, 1 char, 2 cells for
    /// emoji) produces an off-by-N column report on every match after
    /// it on the same row.
    ///
    /// `utf16ToCol` has length `text.utf16.count + 1`; the trailing
    /// sentinel is the column IMMEDIATELY AFTER the last painted
    /// character's rightmost cell — so for a match covering UTF-16
    /// units `[lo, hi)`, the last grid column covered is
    /// `utf16ToCol[hi] - 1`, which handles wide-char tails without a
    /// special case. Trailing empty cells (unwritten) do NOT extend
    /// the sentinel.
    ///
    /// Returns nil for out-of-range rows. Audit H4 / H5.
    public func rowTextWithUTF16ToColMap(row: Int) -> (text: String, utf16ToCol: [Int])? {
        guard row >= 0, row < rows else { return nil }
        var text = ""
        text.reserveCapacity(cols)
        var utf16ToCol: [Int] = []
        utf16ToCol.reserveCapacity(cols + 1)
        var sentinel = 0
        var c = 0
        while c < cols {
            switch cellKind(at: c, row: row) {
            case .character(let ch):
                // Width = run of trailing spacer cells. A narrow char
                // has none (next cell is char or empty); a wide char
                // owns exactly one (alacritty marks col+1 as spacer).
                var next = c + 1
                while next < cols, cellKind(at: next, row: row) == .spacer {
                    next += 1
                }
                for _ in 0..<ch.utf16.count {
                    utf16ToCol.append(c)
                }
                text.append(ch)
                sentinel = next
                c = next
            case .spacer:
                // Orphan spacer (shouldn't occur — alacritty always
                // writes the leading char first). Skip without
                // advancing the sentinel.
                c += 1
            case .invalid:
                // Cell holds a non-zero scalar that fails
                // `Unicode.Scalar` construction — surrogate or
                // out-of-range. alacritty rejects these upstream
                // today, so this branch is defensive. Skip past
                // without truncating the row's haystack so a single
                // hostile cell can't blank out everything to its
                // right (which would cause a regex search to silently
                // miss matches past that column). Audit L-15 / DI-9
                // (2026-04-29).
                //
                // Audit follow-up (2026-04-29): one-shot warning so an
                // alacritty filter regression that lets surrogate /
                // out-of-range scalars through is discoverable rather
                // than silently skipped. Sibling of M-15 / L-17 / M-17.
                BBTerm.didLogInvalidCell.withLock { logged in
                    if !logged {
                        logged = true
                        BBTerm.clampLogger.warning("rowTextWithUTF16ToColMap: encountered .invalid cell at row=\(row, privacy: .public) col=\(c, privacy: .public) — alacritty filter regression?")
                    }
                }
                c += 1
            case .empty:
                // Unwritten cell. Stop walking — trailing empties don't
                // extend the row's text or contribute to the sentinel.
                c = cols
            }
        }
        utf16ToCol.append(sentinel)
        return (text, utf16ToCol)
    }

    /// Number of shell-input characters in `[startCol, endCol]` on
    /// `row` — equal to the DEL count needed to erase the span via
    /// readline. Counts cells whose `cellKind` is `.character` and
    /// excludes spacer / empty cells. A wide CJK glyph at col 0 (one
    /// character, cells 0–1) returns 1.
    ///
    /// Returns nil when the row is outside the snapshot's viewport
    /// (caller falls back to col-span counting for scrollback rows
    /// that aren't in the snapshot — replace requires the match be
    /// on the cursor line, which is always in viewport, so this
    /// fallback never fires in practice). Audit H6.
    public func nonSpacerCellCount(row: Int, startCol: Int, endCol: Int) -> Int? {
        guard row >= 0, row < rows else { return nil }
        guard startCol >= 0, endCol >= startCol, endCol < cols else { return nil }
        var count = 0
        for c in startCol...endCol {
            if case .character = cellKind(at: c, row: row) {
                count += 1
            }
        }
        return count
    }

    public func character(at col: Int, row: Int) -> Character? {
        // Full four-sided bounds check plus explicit cells_len guard.
        // `handle.pointee.cells` is an `UnsafePointer<BBCell>` — its
        // subscript is raw pointer arithmetic with NO bounds
        // assertion, so an out-of-range idx would read arbitrary
        // memory (UB) rather than trap. Belt-and-braces: check idx
        // against cellCount too so a snapshot with a corrupted
        // rows/cols metadata can't turn into a UAF read.
        guard col >= 0, row >= 0, col < cols, row < rows else { return nil }
        // Audit L-19 / EC-9 (2026-04-29): overflow-safe flat index.
        // Bounded today by `MAX_DIM`, so the multiply can't wrap on
        // any in-spec snapshot; the helper exists so a future caller
        // that lifts that bound gets a safe fallback.
        guard let idx = Self.flatIndex(row: row, col: col, cols: cols) else { return nil }
        guard idx < cellCount else { return nil }
        let scalar = handle.pointee.cells[idx].ch
        guard scalar != 0, let us = Unicode.Scalar(scalar) else { return nil }
        return Character(us)
    }

    /// Raw cell pointer for bulk iteration by the renderer. Returned pointer
    /// is valid for the lifetime of this BBSnapshot.
    public var cellsPointer: UnsafePointer<BBCell> {
        handle.pointee.cells
    }

    public var cellCount: Int {
        Int(handle.pointee.cells_len)
    }

    // MARK: - Damage tracking

    /// True when alacritty reported full damage (scroll, insert-mode,
    /// display-offset change — anything that shifts every row's content).
    /// Callers treating this as "repaint everything" are always correct;
    /// the partial `damagedRows` list is a hint for the fast path.
    public var damageIsFull: Bool {
        bb_snap_damage_is_full(handle) != 0
    }

    /// The specific row indices (0..<rows) that changed between this
    /// snapshot and the previous. Empty when `damageIsFull` is true, or
    /// when nothing actually changed. Meaningful only when
    /// `damageIsFull == false`.
    ///
    /// Not cached — calls `bb_snap_damage_rows` each read. Renderers
    /// that consume this should store the result themselves (typical
    /// access pattern: read once per frame in `buildInstances`).
    ///
    /// Handles the `bb_snap_damage_rows` total-count contract (rust-core-4
    /// F2): if the returned `total` exceeds the allocated capacity the
    /// buffer was too small to hold every damaged row; re-allocate at the
    /// reported size and retry exactly once. In practice damage is capped
    /// at the screen rows, so the first pass covers every legitimate case.
    public var damagedRows: [Int] {
        guard !damageIsFull else { return [] }
        let cap = Int(handle.pointee.rows)
        var out = [UInt16](repeating: 0, count: cap)
        let total = out.withUnsafeMutableBufferPointer { buf -> Int in
            guard let base = buf.baseAddress else { return 0 }
            return Int(bb_snap_damage_rows(handle, base, UInt(cap)))
        }
        if total <= cap {
            return out[0..<total].map { Int($0) }
        }
        // Truncation path: re-allocate at the reported total and retry.
        var retry = [UInt16](repeating: 0, count: total)
        let written = retry.withUnsafeMutableBufferPointer { buf -> Int in
            guard let base = buf.baseAddress else { return 0 }
            return Int(bb_snap_damage_rows(handle, base, UInt(total)))
        }
        let n = min(written, retry.count)
        return retry[0..<n].map { Int($0) }
    }

    // MARK: - OSC 8 hyperlink attribution

    /// Non-zero OSC 8 link id associated with the cell at (row, col), or 0
    /// when the cell has no attribution. Resolve to a URL via `linkURL(id:)`.
    /// Out-of-range inputs return 0 (matching the FFI's bounds check).
    public func linkID(row: Int, col: Int) -> UInt32 {
        guard row >= 0, col >= 0, row < rows, col < cols else { return 0 }
        return bb_snap_link_id_at(handle, UInt16(row), UInt16(col))
    }

    /// Resolve an OSC 8 link id to its UTF-8 URL string. The FFI returns a
    /// pointer valid for the lifetime of this snapshot; we copy the bytes
    /// into a Swift String so callers don't need to reason about lifetime.
    /// Returns nil for `id == 0` or an unknown id.
    public func linkURL(id: UInt32) -> String? {
        guard id != 0 else { return nil }
        guard let c = bb_snap_link_url(handle, id) else { return nil }
        return String(cString: c)
    }
}

// MARK: - Accessibility surface -------------------------------------------

/// Narrow read-only view of a grid snapshot, consumed by the NSAccessibility
/// value path on `TerminalView`. Extracted so headless tests can feed a fake
/// grid into the view without needing to construct a real `BBTerm` +
/// `BBSnap`. Production code uses the `BBSnapshot` conformance below.
public protocol A11ySnapshotSource: AnyObject {
    /// Visible rows as text, one `String` per row, with NO trailing
    /// whitespace stripping — the a11y path decides whether to trim, and
    /// the copy / search paths have different needs.
    ///
    /// Wide-glyph spacer cells (`WIDE_CHAR_SPACER`, `LEADING_WIDE_CHAR_SPACER`)
    /// must be skipped so a CJK character or wide emoji appears exactly once
    /// in the returned text, even though it paints two visual cells.
    func visibleRowsAsText() -> [String]

    /// Stable identity for a11y cache invalidation. Equal-identity means
    /// equal content — no need to recompute. Snapshots are immutable and
    /// ref-counted, so the raw pointer address is a sound identity: a new
    /// snapshot always gets a fresh allocation.
    var a11yIdentity: UnsafeRawPointer { get }
}

extension BBSnapshot: A11ySnapshotSource {
    /// Visible rows as text, one String per row. Skips wide-glyph spacer
    /// cells so each wide character (CJK, wide emoji) contributes exactly
    /// one scalar to the row's text.
    public func visibleRowsAsText() -> [String] {
        var out: [String] = []
        out.reserveCapacity(rows)
        let cellsPtr = cellsPointer
        let cellLen = cellCount
        let spacerMask = UInt16(WIDE_CHAR_SPACER) | UInt16(LEADING_WIDE_CHAR_SPACER)
        for r in 0..<rows {
            var chars: [Character] = []
            chars.reserveCapacity(cols)
            for c in 0..<cols {
                // Audit L-19 / EC-9 (2026-04-29): overflow-safe flat
                // index. Today bounded by `MAX_DIM`, so the multiply
                // can't wrap; the helper exists so a future caller
                // that lifts that bound gets a safe fallback.
                guard let idx = Self.flatIndex(row: r, col: c, cols: cols) else { break }
                // `cellsPtr` is a raw UnsafePointer — subscripting past
                // the end is UB, not a trap. Guard against a
                // corrupted snapshot where cells_len drifts below
                // rows*cols.
                guard idx < cellLen else { break }
                let cell = cellsPtr[idx]
                if cell.flags & spacerMask != 0 {
                    continue   // wide-glyph tail, already painted by the leading cell
                }
                // Zero means "unrendered" (blank). Treat as space so column
                // alignment of subsequent non-empty cells is preserved for
                // screen readers that navigate by character.
                let scalar: Unicode.Scalar
                if cell.ch == 0 {
                    scalar = Unicode.Scalar(32)!
                } else {
                    scalar = Unicode.Scalar(cell.ch) ?? Unicode.Scalar(32)!
                }
                chars.append(Character(scalar))
            }
            out.append(String(chars))
        }
        return out
    }

    /// Raw pointer identity for a11y cache invalidation. The underlying
    /// `BBSnap` allocation is retained for the lifetime of this wrapper, so
    /// using the pointer as a key is safe — when the wrapper goes away and a
    /// new one comes in, the address differs.
    public var a11yIdentity: UnsafeRawPointer {
        UnsafeRawPointer(handle)
    }
}

extension String {
    /// Drop trailing whitespace (per `Character.isWhitespace`) without
    /// touching leading whitespace. Used by the a11y path so indented lines
    /// keep their shape while the grid's blank fill at row ends doesn't
    /// bloat the screen-reader readout with trailing spaces.
    public func trimmingTrailingWhitespace() -> String {
        var s = Substring(self)
        while let last = s.last, last.isWhitespace { s = s.dropLast() }
        return String(s)
    }
}
