import Foundation
import BBCore

/// Swift wrapper over the BBCore C ABI. Owns a single BBTerm and guarantees
/// freeing on deinit. Not Sendable — must be used from a single serial queue
/// (the `core` queue in a TerminalSession).
public final class BBTerm {
    public struct Size: Equatable {
        public var cols: UInt16
        public var rows: UInt16
        public init(cols: UInt16, rows: UInt16) {
            self.cols = cols
            self.rows = rows
        }
    }

    public enum Event {
        case title(String)
        case bell
        case cursorShape(Int)
        case osc52Clipboard(String)
        /// Bytes to write back to the PTY (terminal → shell). Generated by
        /// the VT parser in response to DSR, DA1/DA2, and similar queries.
        case ptyWrite(Data)
        /// Shell-emitted working-directory change via OSC 7. Payload is a
        /// decoded, local filesystem path (no `file://` prefix). Fires only
        /// when the Rust core validates scheme == file and host in {empty,
        /// localhost}; matches spec §4.1.
        case cwdChanged(String)
        case fatal(String)
    }

    public typealias EventHandler = (Event) -> Void

    // 'struct BBTerm' is an opaque forward declaration in BBCore.h;
    // Swift imports struct BBTerm * as OpaquePointer throughout.
    private var handle: OpaquePointer?
    private var handler: EventHandler?
    private let ctxBox: UnsafeMutablePointer<EventCtx>

    private final class EventCtx {
        weak var owner: BBTerm?
    }

    public init?(size: Size, scrollback: UInt32 = 10_000) {
        guard let ptr = bb_term_new(size.cols, size.rows, scrollback) else { return nil }
        self.handle = ptr

        let box = UnsafeMutablePointer<EventCtx>.allocate(capacity: 1)
        box.initialize(to: EventCtx())
        self.ctxBox = box

        // Set the weak back-reference after self is fully initialized.
        box.pointee.owner = self
        bb_term_set_event_cb(ptr, BBTerm.eventTrampoline, UnsafeMutableRawPointer(box))
    }

    deinit {
        if let h = handle {
            bb_term_set_event_cb(h, nil, nil)
            bb_term_free(h)
        }
        ctxBox.deinitialize(count: 1)
        ctxBox.deallocate()
    }

    public func onEvent(_ handler: @escaping EventHandler) {
        self.handler = handler
    }

    public func input(_ bytes: [UInt8]) {
        guard let h = handle else { return }
        bytes.withUnsafeBufferPointer { buf in
            bb_term_input(h, buf.baseAddress, UInt(buf.count))
        }
    }

    public func input(_ string: String) {
        input(Array(string.utf8))
    }

    public func resize(to size: Size) {
        guard let h = handle else { return }
        bb_term_resize(h, size.cols, size.rows)
    }

    public func scroll(delta: Int32) {
        guard let h = handle else { return }
        bb_term_scroll(h, delta)
    }

    /// Snap the viewport back to the live grid. Called after any keystroke so
    /// typing always brings the user out of scrollback.
    public func scrollToBottom() {
        guard let h = handle else { return }
        bb_term_scroll_to_bottom(h)
    }

    public func clearAll() {
        guard let h = handle else { return }
        bb_term_clear_all(h)
    }

    /// Update one palette slot. See BBCore.h for slot conventions.
    public func setColor(slot: Int, rgb: UInt32) {
        guard let h = handle else { return }
        bb_term_set_named_color(h, UInt16(slot), rgb)
    }

    /// Extract UTF-8 text between two buffer points. `rectangular` selects
    /// the axis-aligned bounding box between start/end; `false` selects the
    /// prose-style sweep (first line from startCol, middle lines full, last
    /// line to endCol). Lines outside the buffer are silently skipped.
    /// Returns `nil` when the underlying FFI call fails (null handle or
    /// out-of-range arguments).
    public func textRange(
        startLine: Int32, startCol: Int,
        endLine: Int32,   endCol: Int,
        rectangular: Bool
    ) -> String? {
        guard let h = handle else { return nil }
        guard let raw = bb_term_text_range(
            h,
            startLine, UInt16(startCol),
            endLine,   UInt16(endCol),
            rectangular ? 1 : 0
        ) else {
            return nil
        }
        defer { bb_string_release(raw) }
        let buf = UnsafeBufferPointer(start: raw.pointee.bytes, count: Int(raw.pointee.len))
        return String(decoding: buf, as: UTF8.self)
    }

    public func snapshot() -> BBSnapshot? {
        guard let h = handle else { return nil }
        guard let raw = bb_term_take_snapshot(h) else { return nil }
        return BBSnapshot(retaining: raw)
    }

    // MARK: - Event trampoline

    private static let eventTrampoline: @convention(c) (BBEvent, UnsafeMutableRawPointer?) -> Void = { ev, ctx in
        guard let ctx else { return }
        let box = ctx.assumingMemoryBound(to: EventCtx.self)
        guard let owner = box.pointee.owner else { return }
        owner.dispatch(ev)
    }

    private func dispatch(_ ev: BBEvent) {
        guard let handler else { return }
        // BBEventKind is typedef uint32_t in C. ev.kind is UInt32.
        // The BB_EVENT_KIND_* constants are C enum variants; use their integer
        // values directly to avoid Swift 6 cross-module typedef comparison issues.
        switch ev.kind {
        case 1:   // BB_EVENT_KIND_TITLE
            handler(.title(Self.string(from: ev)))
        case 2:   // BB_EVENT_KIND_BELL
            handler(.bell)
        case 3:   // BB_EVENT_KIND_CURSOR_SHAPE
            handler(.cursorShape(Int(ev.i32_arg)))
        case 4:   // BB_EVENT_KIND_OSC52_CLIPBOARD
            handler(.osc52Clipboard(Self.string(from: ev)))
        case 5:   // BB_EVENT_KIND_PTY_WRITE
            handler(.ptyWrite(Self.data(from: ev)))
        case 6:   // BB_EVENT_KIND_CWD_CHANGED
            handler(.cwdChanged(Self.string(from: ev)))
        case 99:  // BB_EVENT_KIND_FATAL
            handler(.fatal(Self.string(from: ev)))
        default:
            break
        }
    }

    private static func string(from ev: BBEvent) -> String {
        guard let ptr = ev.payload, ev.len > 0 else { return "" }
        let buf = UnsafeBufferPointer(start: ptr, count: Int(ev.len))
        return String(decoding: buf, as: UTF8.self)
    }

    private static func data(from ev: BBEvent) -> Data {
        guard let ptr = ev.payload, ev.len > 0 else { return Data() }
        return Data(bytes: ptr, count: Int(ev.len))
    }
}

/// Terminal mode flags mirrored from the Rust `bb_mode` constants.
/// Bits correspond 1-to-1 with the `BBSnap.mode` field.
public struct BBTermMode: OptionSet {
    public let rawValue: UInt32
    public init(rawValue: UInt32) { self.rawValue = rawValue }

    public static let altScreen        = BBTermMode(rawValue: 1 << 0)
    public static let appCursor        = BBTermMode(rawValue: 1 << 1)
    public static let appKeypad        = BBTermMode(rawValue: 1 << 2)
    public static let bracketedPaste   = BBTermMode(rawValue: 1 << 3)
    public static let mouseReportClick = BBTermMode(rawValue: 1 << 4)
    public static let mouseMotion      = BBTermMode(rawValue: 1 << 5)
    public static let mouseDrag        = BBTermMode(rawValue: 1 << 6)
    public static let sgrMouse         = BBTermMode(rawValue: 1 << 7)
    public static let focusInOut       = BBTermMode(rawValue: 1 << 8)
    public static let showCursor       = BBTermMode(rawValue: 1 << 9)
    public static let lineWrap         = BBTermMode(rawValue: 1 << 10)
    // Kitty keyboard protocol. When `disambiguateEscCodes` is set, the encoder
    // must emit CSI u sequences for modified keys so TUIs can distinguish
    // Shift+Enter from Enter, Ctrl+i from Tab, etc.
    public static let disambiguateEscCodes = BBTermMode(rawValue: 1 << 11)
    public static let reportEventTypes     = BBTermMode(rawValue: 1 << 12)
    public static let reportAlternateKeys  = BBTermMode(rawValue: 1 << 13)
    public static let reportAllKeysAsEsc   = BBTermMode(rawValue: 1 << 14)
    public static let reportAssociatedText = BBTermMode(rawValue: 1 << 15)
}

/// Immutable snapshot of the grid. Holds a ref until deinit.
public final class BBSnapshot {
    private let handle: UnsafePointer<BBSnap>

    /// Monotonic sequence id assigned once at init. Every new `BBSnapshot`
    /// gets a strictly larger number than any previously-allocated one.
    /// Used by `MetalRenderer.FrameKey` as a dedup token that — unlike the
    /// raw handle pointer — survives allocator address reuse: an old
    /// snapshot's handle can be freed and a new snapshot's handle can
    /// land at the same address, which would make a pointer-equality
    /// cache skip a legitimate repaint (see comments there).
    public let sequenceID: UInt64
    /// Private atomic counter. Using a static OSAtomic-style increment
    /// via `OSAtomicIncrement64` was considered, but a lock-guarded
    /// UInt64 is plenty given BBSnapshot init happens a few hundred
    /// times per second at most.
    private static let sequenceLock = NSLock()
    private static var nextSequenceID: UInt64 = 0
    private static func allocateSequence() -> UInt64 {
        sequenceLock.lock()
        nextSequenceID &+= 1
        let id = nextSequenceID
        sequenceLock.unlock()
        return id
    }

    init(retaining raw: UnsafePointer<BBSnap>) {
        self.handle = raw
        self.sequenceID = Self.allocateSequence()
    }

    deinit {
        bb_snap_release(handle)
    }

    public var cols: Int { Int(handle.pointee.cols) }
    public var rows: Int { Int(handle.pointee.rows) }
    public var cursorCol: Int { Int(handle.pointee.cursor_col) }
    public var cursorRow: Int { Int(handle.pointee.cursor_row) }
    public var cursorVisible: Bool { handle.pointee.cursor_visible != 0 }
    /// Lines scrolled above the live grid. 0 = pinned to bottom.
    public var displayOffset: Int { Int(handle.pointee.display_offset) }
    /// Total scrollback lines retained (up to the scrollback limit).
    public var historySize: Int { Int(handle.pointee.history_size) }
    /// DECSCUSR cursor shape: 0 = block, 1 = bar/beam, 2 = underline, 3 = hidden.
    public var cursorShape: Int { Int(handle.pointee.cursor_shape) }
    public var mode: UInt32 { handle.pointee.mode }
    public var termMode: BBTermMode { BBTermMode(rawValue: mode) }

    public func character(at col: Int, row: Int) -> Character? {
        // Full four-sided bounds check. Prior code only guarded the
        // upper bound, which left a trap: `cells[negIdx]` on a
        // negative-index access (easy to construct via a caller that
        // passes unclamped coordinates from a scroll-offset calculation)
        // would panic out of Swift's array bounds assertion. Match
        // `linkID(row:col:)`'s pattern of rejecting both ends.
        guard col >= 0, row >= 0, col < cols, row < rows else { return nil }
        let idx = row * cols + col
        let scalar = handle.pointee.cells[idx].ch
        guard scalar != 0, let us = Unicode.Scalar(scalar) else { return nil }
        return Character(us)
    }

    /// Raw cell pointer for bulk iteration by the renderer. Returned pointer
    /// is valid for the lifetime of this BBSnapshot.
    public var cellsPointer: UnsafePointer<BBCell> {
        handle.pointee.cells
    }

    public var cellCount: Int {
        Int(handle.pointee.cells_len)
    }

    // MARK: - OSC 8 hyperlink attribution

    /// Non-zero OSC 8 link id associated with the cell at (row, col), or 0
    /// when the cell has no attribution. Resolve to a URL via `linkURL(id:)`.
    /// Out-of-range inputs return 0 (matching the FFI's bounds check).
    public func linkID(row: Int, col: Int) -> UInt32 {
        guard row >= 0, col >= 0, row < rows, col < cols else { return 0 }
        return bb_snap_link_id_at(handle, UInt16(row), UInt16(col))
    }

    /// Resolve an OSC 8 link id to its UTF-8 URL string. The FFI returns a
    /// pointer valid for the lifetime of this snapshot; we copy the bytes
    /// into a Swift String so callers don't need to reason about lifetime.
    /// Returns nil for `id == 0` or an unknown id.
    public func linkURL(id: UInt32) -> String? {
        guard id != 0 else { return nil }
        guard let c = bb_snap_link_url(handle, id) else { return nil }
        return String(cString: c)
    }
}

// MARK: - Accessibility surface -------------------------------------------

/// Narrow read-only view of a grid snapshot, consumed by the NSAccessibility
/// value path on `TerminalView`. Extracted so headless tests can feed a fake
/// grid into the view without needing to construct a real `BBTerm` +
/// `BBSnap`. Production code uses the `BBSnapshot` conformance below.
public protocol A11ySnapshotSource: AnyObject {
    /// Visible rows as text, one `String` per row, with NO trailing
    /// whitespace stripping — the a11y path decides whether to trim, and
    /// the copy / search paths have different needs.
    ///
    /// Wide-glyph spacer cells (`WIDE_CHAR_SPACER`, `LEADING_WIDE_CHAR_SPACER`)
    /// must be skipped so a CJK character or wide emoji appears exactly once
    /// in the returned text, even though it paints two visual cells.
    func visibleRowsAsText() -> [String]

    /// Stable identity for a11y cache invalidation. Equal-identity means
    /// equal content — no need to recompute. Snapshots are immutable and
    /// ref-counted, so the raw pointer address is a sound identity: a new
    /// snapshot always gets a fresh allocation.
    var a11yIdentity: UnsafeRawPointer { get }
}

extension BBSnapshot: A11ySnapshotSource {
    /// Visible rows as text, one String per row. Skips wide-glyph spacer
    /// cells so each wide character (CJK, wide emoji) contributes exactly
    /// one scalar to the row's text.
    public func visibleRowsAsText() -> [String] {
        var out: [String] = []
        out.reserveCapacity(rows)
        let cellsPtr = cellsPointer
        let spacerMask = UInt16(WIDE_CHAR_SPACER) | UInt16(LEADING_WIDE_CHAR_SPACER)
        for r in 0..<rows {
            var chars: [Character] = []
            chars.reserveCapacity(cols)
            for c in 0..<cols {
                let cell = cellsPtr[r * cols + c]
                if cell.flags & spacerMask != 0 {
                    continue   // wide-glyph tail, already painted by the leading cell
                }
                // Zero means "unrendered" (blank). Treat as space so column
                // alignment of subsequent non-empty cells is preserved for
                // screen readers that navigate by character.
                let scalar: Unicode.Scalar
                if cell.ch == 0 {
                    scalar = Unicode.Scalar(32)!
                } else {
                    scalar = Unicode.Scalar(cell.ch) ?? Unicode.Scalar(32)!
                }
                chars.append(Character(scalar))
            }
            out.append(String(chars))
        }
        return out
    }

    /// Raw pointer identity for a11y cache invalidation. The underlying
    /// `BBSnap` allocation is retained for the lifetime of this wrapper, so
    /// using the pointer as a key is safe — when the wrapper goes away and a
    /// new one comes in, the address differs.
    public var a11yIdentity: UnsafeRawPointer {
        UnsafeRawPointer(handle)
    }
}

extension String {
    /// Drop trailing whitespace (per `Character.isWhitespace`) without
    /// touching leading whitespace. Used by the a11y path so indented lines
    /// keep their shape while the grid's blank fill at row ends doesn't
    /// bloat the screen-reader readout with trailing spaces.
    public func trimmingTrailingWhitespace() -> String {
        var s = Substring(self)
        while let last = s.last, last.isWhitespace { s = s.dropLast() }
        return String(s)
    }
}
