//! P4.4 — OSC 8 link-table 1 MiB intern-cap recovery contract.
//!
//! `core/src/lib.rs` (`bb_term_take_snapshot`, around the
//! `OSC8_TOTAL_INTERN_BYTES_CAP = 1 MiB` constant) interns each unique
//! OSC 8 URI into `BBTerm::uri_cstr_cache` so cells that re-use a URL
//! across snapshots share one `Arc<CStr>`. The cache is bounded by a
//! global byte-budget: once `uri_cache_bytes + new_uri.len() > 1 MiB`,
//! every distinct new URI drops to `link_id = 0` instead of allocating
//! a fresh entry. Eviction would dangle pointers held by live
//! snapshots, so the cap is intentionally drop-not-evict.
//!
//! Adversarial reviewer concern: a hostile remote can saturate the cap
//! with 257 × 4 KiB unique URIs. After that, every legitimate later
//! OSC 8 (`gh issue`, `npm warn`'s clickable link, `man`'s `less`
//! footer) drops to no-link. If the cap is sticky for the lifetime of
//! the `BBTerm`, the user must restart the app to recover.
//!
//! The recovery surface is narrow:
//!   - `bb_term_clear_all` (⌘K, lib.rs:3219) MUST drop unreferenced
//!     entries. The implementation retains entries whose `Arc::strong
//!     _count > 1` (still pointed-to by a live snapshot's `links` Vec)
//!     and re-derives `uri_cache_bytes` from the survivors.
//!   - `bb_term_free` + `bb_term_new` always reset (a fresh `BBTerm`
//!     starts with `uri_cstr_cache: HashMap::new(), uri_cache_bytes: 0`,
//!     lib.rs:1796-1797).
//!
//! No prior test pinned this contract. The neighbouring test in
//! lib.rs (`osc8_intern_cap_drops_links_past_1mib`, line 5656) only
//! pins the saturation direction — it never exercises clear or free
//! against a saturated cap. This file covers all three legs:
//!   1. Saturation at exactly the 256/257 boundary.
//!   2. `bb_term_clear_all` recovery (snapshot released first, so
//!      no Arc keeps entries pinned).
//!   3. `bb_term_free` + `bb_term_new` recovery.
//!
//! ## Pre-flight memory & time cost
//!
//! Per test:
//!   - 256 unique URIs × 4096 B = exactly 1 MiB of cumulative URI
//!     bytes interned in `uri_cstr_cache`.
//!   - The OSC 8 input stream is ~1 MiB (256 × ~4110 B sequences).
//!   - Snapshot `cells` Vec for an 80×24 grid = ~80×24×24 B ≈ 46 KiB.
//!   - Snapshot `links` Vec ≤ 257 × `Arc<CStr>` (one pointer each, the
//!     CStr storage is shared with the cache via `Arc::clone`).
//!   - Peak working set per test ≈ 4-5 MiB (input buffer + cache +
//!     snapshot + transient Phase-1 Vec). All released before the
//!     next test runs.
//!   - Wall time per test on an M-series Mac: well under 1 s. The
//!     dominant cost is the 1 MiB ASCII allocation and one snapshot
//!     pass over a 1920-cell grid.
//!
//! Total file overhead is bounded by ~5 MiB peak across three tests
//! that run sequentially under `cargo test --test`. None of the tests
//! holds two BBTerms live at once.

use blackbird_core as bc;

/// Build an OSC 8 sequence whose URI is exactly 4096 bytes long, using
/// `idx` as a unique 6-digit zero-padded prefix. All 256 distinct URIs
/// generated by `make_osc8(0..=255)` differ in the prefix and have the
/// same total length, so the cap arithmetic is exact:
/// `256 × 4096 = 1_048_576 = 1 MiB`.
///
/// The returned bytes form a complete OSC 8 hyperlink span: open, one
/// printable `X` cell, close. The terminal records the `X` cell with
/// the URI as its OSC 8 attribution.
fn make_osc8(idx: usize) -> Vec<u8> {
    // `https://x.test/000000/` is the prefix; `idx` lands in the 6-digit
    // slot. Any 6-digit decimal up to 999_999 fits — we only ever go up
    // to 256, so leading zeros guarantee a constant prefix length.
    let prefix = format!("https://x.test/{idx:06}/");
    debug_assert_eq!(prefix.len(), 22, "prefix must be exactly 22 bytes");
    let pad_len = 4096 - prefix.len();
    let mut uri = String::with_capacity(4096);
    uri.push_str(&prefix);
    uri.extend(std::iter::repeat('a').take(pad_len));
    debug_assert_eq!(uri.len(), 4096, "URI must be exactly 4096 bytes");

    let mut seq = Vec::with_capacity(4096 + 16);
    seq.extend_from_slice(b"\x1b]8;;");
    seq.extend_from_slice(uri.as_bytes());
    seq.extend_from_slice(b"\x1b\\X\x1b]8;;\x1b\\");
    seq
}

/// Feed `n` distinct 4 KiB OSC 8 sequences (indices 0..n) into a
/// freshly-allocated 80×24 BBTerm. The grid holds 1920 cells, so up to
/// 1920 sequential `X` cells fit without scrolling — comfortably more
/// than the 257 we ever emit. Returns the term pointer; the caller is
/// responsible for `bb_term_free`.
unsafe fn term_with_n_links(n: usize) -> *mut bc::BBTerm {
    let term = bc::bb_term_new(80, 24, 100);
    assert!(!term.is_null(), "bb_term_new must not fail");
    // Concatenate all sequences into a single input buffer. The parser
    // handles them identically to N separate input calls (Phase 1 walks
    // the resulting grid once at snapshot time).
    let mut buf: Vec<u8> = Vec::with_capacity(n * 4112);
    for i in 0..n {
        buf.extend(make_osc8(i));
    }
    bc::bb_term_input(term, buf.as_ptr(), buf.len());
    term
}

/// Cell `i` of a sequential write into an 80×24 grid lands at
/// (row = i / 80, col = i % 80). With 257 cells we land in rows 0-3.
fn cell_at(i: usize) -> (u16, u16) {
    ((i / 80) as u16, (i % 80) as u16)
}

/// TEST 1 — Cap saturates at exactly 256 × 4 KiB and the 257th URI
/// drops to `link_id = 0`. Pins the boundary stated in the source
/// comment (`OSC8_TOTAL_INTERN_BYTES_CAP = 1024 * 1024`) so a future
/// refactor that nudges the constant or reorders the byte-budget
/// check trips the test.
#[test]
fn osc8_link_cap_saturates_at_1_mib() {
    unsafe {
        // Stage 1: feed the 256 cap-filling URIs and snapshot once.
        // After this, `uri_cache_bytes == 1_048_576` exactly.
        let term = term_with_n_links(256);
        let snap1 = bc::bb_term_take_snapshot(term);
        assert!(!snap1.is_null(), "first snapshot must succeed");

        // Every one of the 256 cells must carry a non-zero link_id.
        // The 256th URI is the boundary: bytes_check is
        // `1_044_480 + 4096 = 1_048_576`, which is NOT > the cap, so it
        // still interns.
        for i in 0..256 {
            let (row, col) = cell_at(i);
            let id = bc::bb_snap_link_id_at(snap1, row, col);
            assert_ne!(
                id, 0,
                "cell {i} (row={row}, col={col}) must have a live link_id \
                 before the cap fires; URI #{i} fits within the 1 MiB budget"
            );
        }

        // Release the snapshot so the next phase doesn't artificially
        // pin Arcs (irrelevant to saturation, but keeps the working
        // set lean — the 256 Arcs in `snap1.links` would otherwise live
        // until the function returns).
        bc::bb_snap_release(snap1);

        // Stage 2: feed the 257th distinct URI into the SAME term.
        // `uri_cache_bytes` is still 1 MiB from Stage 1 (clear_all was
        // not called). Phase 2 of the snapshot will iterate all 257
        // unique URIs Phase 1 collects from the grid:
        //   - URIs 0..255 are already in `uri_cstr_cache` → hot-path
        //     `Arc::clone`, no byte-cap check.
        //   - URI 256 is new → bytes_check is
        //     `1_048_576 + 4096 = 1_052_672 > 1_048_576` → drops to None
        //     → cell's `link_id = 0`.
        let seq257 = make_osc8(256);
        bc::bb_term_input(term, seq257.as_ptr(), seq257.len());

        let snap2 = bc::bb_term_take_snapshot(term);
        assert!(!snap2.is_null(), "second snapshot must succeed");

        let (row257, col257) = cell_at(256);
        let id257 = bc::bb_snap_link_id_at(snap2, row257, col257);
        assert_eq!(
            id257, 0,
            "cell 256 (the 257th OSC 8) must drop to link_id = 0: \
             the 1 MiB cap is full and a new 4 KiB URI cannot be \
             interned. Got link_id={id257}."
        );

        // Cross-check: the first 256 cells still resolve. The cap-trip
        // for the 257th must not retroactively invalidate prior entries
        // — they were already in the cache, the byte-cap check only
        // gates fresh insertions.
        for i in 0..256 {
            let (row, col) = cell_at(i);
            let id = bc::bb_snap_link_id_at(snap2, row, col);
            assert_ne!(
                id, 0,
                "cell {i} must STILL have a live link_id after the \
                 cap fires; the cap drops new entries, never evicts \
                 existing ones (eviction would dangle pointers held \
                 by live snapshots)"
            );
        }

        bc::bb_snap_release(snap2);
        bc::bb_term_free(term);
    }
}

/// TEST 2 — `bb_term_clear_all` recovers the cap once no live snapshot
/// references the interned entries.
///
/// Contract observed in lib.rs:3275-3277:
/// ```text
/// bb.uri_cstr_cache.retain(|_uri, arc| Arc::strong_count(arc) > 1);
/// bb.uri_cache_bytes = bb.uri_cstr_cache.keys().map(|k| k.len()).sum();
/// ```
/// "Retain only entries with `strong_count > 1`" means: drop entries
/// that are referenced by NOTHING else (the cache map's own clone is
/// the sole owner). After we `bb_snap_release(snap1)`, the 256 Arcs
/// in `snap1.links` drop their refcounts; each cache entry's count
/// falls to 1 (just the cache map), making them eligible for removal.
///
/// This is the expected recovery path the comment in lib.rs:3258-3260
/// describes:
///
/// > 5. `uri_cstr_cache` / `uri_cache_bytes` — pre-clear OSC 8
/// >    cache flood blocked legitimate post-clear OSC 8 links
/// >    until app relaunch (the 1 MiB byte-cap stayed exhausted).
///
/// If a future refactor weakens the retain logic (e.g., always-keep
/// for any reason, or fails to recompute `uri_cache_bytes`), the
/// post-clear snapshot's 257-th URI would still drop to `link_id = 0`
/// and this test would fail.
#[test]
fn osc8_link_cap_resets_on_clear_all() {
    unsafe {
        // Saturate the cap (256 × 4 KiB exactly, then push the 257th
        // through to confirm we're truly at the cap-tripped state).
        let term = term_with_n_links(256);
        let snap_pre = bc::bb_term_take_snapshot(term);
        assert!(!snap_pre.is_null(), "pre-clear snapshot must succeed");
        // CRITICAL: release before clear_all. Otherwise the 256 Arcs in
        // `snap_pre.links` keep `strong_count > 1` for every cache
        // entry, the retain predicate fires false on each, and clear_all
        // is a no-op for the cap. Releasing here mirrors the realistic
        // sequence: the renderer holds at most one or two snapshots at
        // a time, all dropped before ⌘K runs.
        bc::bb_snap_release(snap_pre);

        // Sanity: the 257th still drops at this point. If this failed,
        // we never actually hit the cap and the recovery test would be
        // measuring nothing.
        let seq_pre_257 = make_osc8(256);
        bc::bb_term_input(term, seq_pre_257.as_ptr(), seq_pre_257.len());
        let snap_pre_257 = bc::bb_term_take_snapshot(term);
        assert!(!snap_pre_257.is_null());
        let (row_pre, col_pre) = cell_at(256);
        assert_eq!(
            bc::bb_snap_link_id_at(snap_pre_257, row_pre, col_pre),
            0,
            "pre-clear: 257th URI must be dropped — confirming we're \
             at the cap-tripped state before testing recovery"
        );
        bc::bb_snap_release(snap_pre_257);

        // The cap is now tripped AND no live snapshot pins the cache
        // entries. clear_all must drop all 256 entries.
        bc::bb_term_clear_all(term);

        // Post-clear: feed a fresh OSC 8 with a never-before-seen URI.
        // If the cap reset, `uri_cache_bytes == 0` and this URI gets a
        // live link_id. If it didn't, we're still over budget and the
        // URI drops to 0 (the bug the reviewer flagged).
        let fresh_seq = make_osc8(900); // index unused above
        bc::bb_term_input(term, fresh_seq.as_ptr(), fresh_seq.len());

        let snap_post = bc::bb_term_take_snapshot(term);
        assert!(!snap_post.is_null(), "post-clear snapshot must succeed");

        // After clear_all the cursor returns to (0, 0) (CSI [H is part
        // of the clear-all escape: `\x1b[H\x1b[2J\x1b[3J`). So the new
        // X lands at (0, 0).
        let post_id = bc::bb_snap_link_id_at(snap_post, 0, 0);
        assert_ne!(
            post_id, 0,
            "post-clear: a fresh OSC 8 must intern successfully — \
             `bb_term_clear_all` is documented (lib.rs:3258-3260) to \
             drop unreferenced cache entries and reset uri_cache_bytes \
             so legitimate post-clear hyperlinks are clickable. Got \
             link_id={post_id}, indicating the cap is still tripped \
             after the wipe."
        );

        // And resolve the URL to confirm it's the new one, not stale.
        let url_ptr = bc::bb_snap_link_url(snap_post, post_id);
        assert!(!url_ptr.is_null(), "post-clear link_id must resolve");
        let url = std::ffi::CStr::from_ptr(url_ptr as *const _)
            .to_string_lossy()
            .into_owned();
        assert!(
            url.starts_with("https://x.test/000900/"),
            "post-clear URL must be the fresh one (index 900), got: \
             {} (first 64 bytes)",
            &url[..url.len().min(64)]
        );

        bc::bb_snap_release(snap_post);
        bc::bb_term_free(term);
    }
}

/// TEST 2b — `bb_term_clear_all` MUST reset the cap even when a
/// snapshot is still held across the clear. Audit S5-002.
///
/// Production Swift code (`TerminalSession.clearAll`) calls
/// `bbterm.clearAll()` while `TerminalView.currentSnapshot` still
/// references the pre-clear snapshot — the publish-immediate flow
/// runs the FFI side first, then publishes the fresh snapshot, so
/// the prior snapshot is still alive at the moment of the FFI call.
/// With the old `retain(strong_count > 1)` predicate, every cache
/// entry's Arc count is >1 (the held snapshot pins each URI), so
/// retain keeps every entry and `uri_cache_bytes` remains saturated.
/// Post-clear OSC 8 hyperlinks silently lose attribution.
///
/// The realistic-Swift sequence here keeps `snap_pre` alive across
/// `bb_term_clear_all` and asserts:
///   (a) a fresh post-clear URI interns successfully (cap reset)
///   (b) `snap_pre`'s pre-clear URI is still resolvable (no UAF —
///       the snapshot's own Arc<CStr> clones independently keep the
///       CStrs alive even though the cache dropped its references).
#[test]
fn osc8_link_cap_resets_on_clear_all_even_with_live_snapshot() {
    unsafe {
        let term = term_with_n_links(256);
        let snap_pre = bc::bb_term_take_snapshot(term);
        assert!(!snap_pre.is_null(), "pre-clear snapshot must succeed");

        // Confirm the cap is tripped before testing recovery.
        let seq_257 = make_osc8(256);
        bc::bb_term_input(term, seq_257.as_ptr(), seq_257.len());
        let snap_full = bc::bb_term_take_snapshot(term);
        assert!(!snap_full.is_null());
        let (r257, c257) = cell_at(256);
        assert_eq!(
            bc::bb_snap_link_id_at(snap_full, r257, c257),
            0,
            "pre-clear: 257th URI must be dropped — confirms cap tripped"
        );
        bc::bb_snap_release(snap_full);

        // CRITICAL DIFFERENCE from `osc8_link_cap_resets_on_clear_all`:
        // snap_pre stays ALIVE here, mirroring how Swift's
        // currentSnapshot pins the prior snapshot across clearAll().
        bc::bb_term_clear_all(term);

        // Post-clear: a fresh URI must now intern despite the
        // held-snapshot pinning. Pre-fix this fails because
        // `retain(strong_count > 1)` keeps every entry.
        let fresh_seq = make_osc8(900);
        bc::bb_term_input(term, fresh_seq.as_ptr(), fresh_seq.len());
        let snap_post = bc::bb_term_take_snapshot(term);
        assert!(!snap_post.is_null());

        let post_id = bc::bb_snap_link_id_at(snap_post, 0, 0);
        assert_ne!(
            post_id, 0,
            "post-clear: a fresh OSC 8 must intern successfully even \
             when a pre-clear snapshot is still live. Audit S5-002: \
             the prior retain(strong_count > 1) predicate kept every \
             cache entry when Swift held a snapshot across clearAll, \
             leaving uri_cache_bytes saturated and post-clear links \
             silently dropping to link_id=0."
        );

        // Memory safety: snap_pre's own Arc clones must independently
        // keep its URIs alive even though the cache dropped its refs.
        // Resolve link_id=1 on snap_pre (the first interned URI) and
        // verify it still points to a non-null CStr.
        let pre_url_ptr = bc::bb_snap_link_url(snap_pre, 1);
        assert!(
            !pre_url_ptr.is_null(),
            "pre-clear snapshot's URI must still resolve after \
             bb_term_clear_all dropped the cache — the snapshot's own \
             Arc<CStr> clone keeps the byte buffer alive."
        );

        bc::bb_snap_release(snap_post);
        bc::bb_snap_release(snap_pre);
        bc::bb_term_free(term);
    }
}

/// TEST 3 — `bb_term_free` + `bb_term_new` recovers the cap.
///
/// A fresh `BBTerm` starts with `uri_cstr_cache: HashMap::new()` and
/// `uri_cache_bytes: 0` (lib.rs:1796-1797). The cap is per-instance
/// state; `bb_term_free` drops the entire `Box<BBTerm>` — including
/// the cache — and the next `bb_term_new` is unrelated. This is the
/// "app relaunch" path mentioned in the source comment, but at FFI
/// granularity.
///
/// The previous two tests would also catch a regression that broke
/// this — but only via the same mechanism. Pinning it explicitly
/// guards against a hypothetical refactor that introduces a static or
/// thread-local cache shared across BBTerm instances (the cap would
/// then survive even free + new).
#[test]
fn osc8_link_cap_resets_on_free_and_new() {
    unsafe {
        // Saturate.
        let term1 = term_with_n_links(256);
        let snap = bc::bb_term_take_snapshot(term1);
        assert!(!snap.is_null());
        // Sanity: confirm the 257th drops on term1.
        let seq257 = make_osc8(256);
        bc::bb_term_input(term1, seq257.as_ptr(), seq257.len());
        let snap_full = bc::bb_term_take_snapshot(term1);
        assert!(!snap_full.is_null());
        let (r, c) = cell_at(256);
        assert_eq!(
            bc::bb_snap_link_id_at(snap_full, r, c),
            0,
            "term1: cap must be tripped before we tear it down — the \
             test relies on this baseline"
        );
        bc::bb_snap_release(snap);
        bc::bb_snap_release(snap_full);

        // Tear down the saturated term completely. After this, no
        // BBTerm state survives — the new term is a distinct heap
        // allocation with a fresh cache.
        bc::bb_term_free(term1);

        // Fresh term. Cap is back to zero bytes used.
        let term2 = bc::bb_term_new(80, 24, 100);
        assert!(!term2.is_null(), "fresh bb_term_new must succeed");

        // Reuse index 0's URI — also exercises that the cache is
        // genuinely empty (a leaked-shared cache would still have
        // index 0 from term1).
        let fresh_seq = make_osc8(0);
        bc::bb_term_input(term2, fresh_seq.as_ptr(), fresh_seq.len());

        let snap_fresh = bc::bb_term_take_snapshot(term2);
        assert!(!snap_fresh.is_null());
        let fresh_id = bc::bb_snap_link_id_at(snap_fresh, 0, 0);
        assert_ne!(
            fresh_id, 0,
            "fresh BBTerm: a single OSC 8 must intern successfully. \
             The 1 MiB cap is per-BBTerm state (lib.rs:1796-1797 init); \
             a regression that introduced a process-global cache would \
             let term1's saturation leak across `bb_term_free` and \
             this assertion would fail."
        );

        bc::bb_snap_release(snap_fresh);
        bc::bb_term_free(term2);
    }
}
